{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "NONE",
    "body": "I'm trying to make an UI attachment in a plugin, but it doesn't seem to work and runs into errors.\r\nI tried various different variations of the code below:\r\n\r\n```ruby\r\nNeovim.logger << 'test!'\r\n\r\nNeovim.plugin do |plug|\r\n  plug.ui_attach(999, 999, {}) do |*a|\r\n    Neovim.logger << a.inspect\r\n  end\r\nend\r\n```\r\n\r\nWith and without block argument, with value in the hashmap and entirely without a third argument, but I'm always getting the same error, so I suspect that it's a plugin issue. Otherwise any hints are welcome.\r\n\r\nThe error appears once I call `:UpdateRemotePlugins` (I'm using https://github.com/junegunn/vim-plug).\r\n\r\n## Versions\r\nmacOS 14.1.1 Sonoma\r\nRuby: 3.2.2 (rbenv 1.2.0)\r\nGem: 3.4.12\r\nNeovim-Ruby: 0.9.1\r\nNeovim: 0.9.4\r\n\r\n## Neovim error message\r\n```\r\nfunction remote#host#UpdateRemotePlugins[6]..<SNR>61_RegistrationCommands[15]..remote#\r\nhost#Require[10]..provider#ruby#Require[8]..provider#Poll, line 7\r\nVim(if):Error invoking 'poll' on channel 5:^@Invalid channel: 5\r\nfunction remote#host#UpdateRemotePlugins[6]..<SNR>61_RegistrationCommands[15]..remote#\r\nhost#Require[10]..provider#ruby#Require[8]..provider#Poll, line 17\r\nFailed to load ruby host. You can try to see what happened by starting nvim with $NVIM\r\n_RUBY_LOG_FILE set and opening the generated log file. Also, the host stderr is available in messages.\r\nremote/host: generated rplugin manifest: /Users/huluk/.local/share/nvim/rplugin.vim\r\n```\r\n\r\n## Error logs\r\n```\r\n# Logfile created on 2023-11-25 17:07:28 +0100 by logger.rb/v1.5.3\r\n{\"_level\":\"DEBUG\",\"_time\":\"2023-11-25T17:07:28.708601\",\"_class\":\"Neovim::EventLoop\",\"_method\":\"run\",\"exception\":\"EOFError\",\"message\":\"end of file reached\"}\r\n{\"_level\":\"DEBUG\",\"_time\":\"2023-11-25T17:07:28.720948\",\"_class\":\"Neovim::EventLoop\",\"_method\":\"run\",\"exception\":\"EOFError\",\"message\":\"end of file reached\",\"backtrace\":[\"/usr/local/var/rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/neovim-0.9.1/lib/neovim/connection.rb:47:in `readpartial'\",\"/usr/local/var/rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/neovim-0.9.1/lib/neovim/connection.rb:47:in `read'\",\"/usr/local/var/rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/neovim-0.9.1/lib/neovim/connection.rb:47:in `read'\",\"/usr/local/var/rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/neovim-0.9.1/lib/neovim/event_loop.rb:109:in `read'\",\"/usr/local/var/rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/neovim-0.9.1/lib/neovim/event_loop.rb:80:in `block in run'\",\"/usr/local/var/rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/neovim-0.9.1/lib/neovim/event_loop.rb:75:in `loop'\",\"/usr/local/var/rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/neovim-0.9.1/lib/neovim/event_loop.rb:75:in `run'\",\"/usr/local/var/rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/neovim-0.9.1/lib/neovim/session.rb:35:in `run'\",\"/usr/local/var/rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/neovim-0.9.1/lib/neovim/host.rb:29:in `run'\",\"/usr/local/var/rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/neovim-0.9.1/lib/neovim/host.rb:17:in `run'\",\"/usr/local/var/rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/neovim-0.9.1/lib/neovim/host/cli.rb:33:in `run'\",\"/usr/local/var/rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/neovim-0.9.1/exe/neovim-ruby-host:5:in `<top (required)>'\",\"/usr/local/var/rbenv/versions/3.2.2/bin/neovim-ruby-host:25:in `load'\",\"/usr/local/var/rbenv/versions/3.2.2/bin/neovim-ruby-host:25:in `<main>'\"]}\r\ntest!\r\n```",
    "closed_at": null,
    "comment_data": [
        {
            "author_association": "MEMBER",
            "body": "I think there are a couple things causing this... first of all it seems like writing to `Neovim.logger` from a remote plugin breaks the rpc connection. Try removing those lines that write to the logger.\r\n\r\nThe next thing you're going to run into though, is that you're calling `ui_attach` on the remote plugin DSL object, not a neovim client. I think this closer to what you want, although I'm not sure if this works either:\r\n\r\n```ruby\r\nNeovim.plugin do |plug|\r\n  plug.command(:StartMyUI) do |client|\r\n    client.ui_attach(999, 999, {})\r\n  end\r\nend\r\n```\r\n\r\nThat said, I'm not sure if you want to spawn a UI within a remote plugin like this... I'm pretty unfamiliar with writing UI clients but my understanding was that the UI process should be responsible for starting an embedded nvim process, which it sends the `nvim_ui_attach` rpc when it's ready to draw (see docs: https://neovim.io/doc/user/ui.html). Maybe @justinmk could point to better resources/examples? Sorry I'm not super helpful here.",
            "created_at": "2023-11-25T23:14:44Z",
            "html_url": "https://github.com/neovim/neovim-ruby/issues/101#issuecomment-1826439959",
            "id": 1826439959,
            "issue_url": "https://api.github.com/repos/neovim/neovim-ruby/issues/101",
            "node_id": "IC_kwDOAS_2Ds5s3UMX",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim-ruby/issues/comments/1826439959/reactions"
            },
            "updated_at": "2023-11-25T23:14:44Z",
            "url": "https://api.github.com/repos/neovim/neovim-ruby/issues/comments/1826439959",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/566993?v=4",
                "events_url": "https://api.github.com/users/alexgenco/events{/privacy}",
                "followers_url": "https://api.github.com/users/alexgenco/followers",
                "following_url": "https://api.github.com/users/alexgenco/following{/other_user}",
                "gists_url": "https://api.github.com/users/alexgenco/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/alexgenco",
                "id": 566993,
                "login": "alexgenco",
                "node_id": "MDQ6VXNlcjU2Njk5Mw==",
                "organizations_url": "https://api.github.com/users/alexgenco/orgs",
                "received_events_url": "https://api.github.com/users/alexgenco/received_events",
                "repos_url": "https://api.github.com/users/alexgenco/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/alexgenco/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/alexgenco/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/alexgenco"
            }
        }
    ],
    "comments": 1,
    "comments_url": "https://api.github.com/repos/neovim/neovim-ruby/issues/101/comments",
    "created_at": "2023-11-25T16:30:18Z",
    "events_url": "https://api.github.com/repos/neovim/neovim-ruby/issues/101/events",
    "html_url": "https://github.com/neovim/neovim-ruby/issues/101",
    "id": 2010719610,
    "labels": [],
    "labels_url": "https://api.github.com/repos/neovim/neovim-ruby/issues/101/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "I_kwDOAS_2Ds532SV6",
    "number": 101,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 0,
        "url": "https://api.github.com/repos/neovim/neovim-ruby/issues/101/reactions"
    },
    "repository_url": "https://api.github.com/repos/neovim/neovim-ruby",
    "state": "open",
    "state_reason": null,
    "timeline_url": "https://api.github.com/repos/neovim/neovim-ruby/issues/101/timeline",
    "title": "UI Attach runs into error",
    "updated_at": "2023-11-25T23:14:45Z",
    "url": "https://api.github.com/repos/neovim/neovim-ruby/issues/101",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/127309?v=4",
        "events_url": "https://api.github.com/users/Huluk/events{/privacy}",
        "followers_url": "https://api.github.com/users/Huluk/followers",
        "following_url": "https://api.github.com/users/Huluk/following{/other_user}",
        "gists_url": "https://api.github.com/users/Huluk/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/Huluk",
        "id": 127309,
        "login": "Huluk",
        "node_id": "MDQ6VXNlcjEyNzMwOQ==",
        "organizations_url": "https://api.github.com/users/Huluk/orgs",
        "received_events_url": "https://api.github.com/users/Huluk/received_events",
        "repos_url": "https://api.github.com/users/Huluk/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/Huluk/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/Huluk/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/Huluk"
    }
}