{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "NONE",
    "body": "### Neovim version (nvim -v)\n\n0.6.1\n\n### Vim (not Nvim) behaves the same?\n\nn/a\n\n### Operating system/version\n\nmac os 11.6.2\n\n### Terminal name/version\n\niTerm2\n\n### $TERM environment variable\n\nxterm-256color\n\n### Installation\n\nbrew install neovim\n\n### How to reproduce the issue\n\n:checkhealth provider results in\r\n## Python 3 provider (optional)\r\n  - INFO: Using: g:python3_host_prog = \"/usr/local/bin/python3.9\"\r\n  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.\r\n  - INFO: Executable: Not found\r\n\n\n### Expected behavior\n\nTo find my installed python3:\r\n\r\n➜  ~ which python3\r\n/Library/Frameworks/Python.framework/Versions/3.10/bin/python3\r\n\r\n➜  ~ file /Library/Frameworks/Python.framework/Versions/3.10/bin/python3\r\n/Library/Frameworks/Python.framework/Versions/3.10/bin/python3: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64:Mach-O 64-bit executable arm64]\r\n/Library/Frameworks/Python.framework/Versions/3.10/bin/python3 (for architecture x86_64):Mach-O 64-bit executable x86_64\r\n/Library/Frameworks/Python.framework/Versions/3.10/bin/python3 (for architecture arm64):\tMach-O 64-bit executable arm64\n\n### Actual behavior\n\n:checkhealth provider results in\r\n## Python 3 provider (optional)\r\n  - INFO: Using: g:python3_host_prog = \"/usr/local/bin/python3.9\"\r\n  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.\r\n  - INFO: Executable: Not found ",
    "closed_at": "2022-01-24T17:41:16Z",
    "comment_data": [
        {
            "author_association": "MEMBER",
            "body": "Did you install `pynvim`?",
            "created_at": "2022-01-23T02:23:43Z",
            "html_url": "https://github.com/neovim/neovim/issues/17172#issuecomment-1019398329",
            "id": 1019398329,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/17172",
            "node_id": "IC_kwDOAPphoM48wsi5",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1019398329/reactions"
            },
            "updated_at": "2022-01-23T02:23:43Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1019398329",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/35768171?v=4",
                "events_url": "https://api.github.com/users/zeertzjq/events{/privacy}",
                "followers_url": "https://api.github.com/users/zeertzjq/followers",
                "following_url": "https://api.github.com/users/zeertzjq/following{/other_user}",
                "gists_url": "https://api.github.com/users/zeertzjq/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/zeertzjq",
                "id": 35768171,
                "login": "zeertzjq",
                "node_id": "MDQ6VXNlcjM1NzY4MTcx",
                "organizations_url": "https://api.github.com/users/zeertzjq/orgs",
                "received_events_url": "https://api.github.com/users/zeertzjq/received_events",
                "repos_url": "https://api.github.com/users/zeertzjq/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/zeertzjq/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/zeertzjq/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/zeertzjq"
            }
        },
        {
            "author_association": "NONE",
            "body": "@zeertzjq yes, it is installed. See as per below:\r\n➜  ~ pip3 install pynvim                                                                                                                                                           <<<\r\nRequirement already satisfied: pynvim in ./Library/Python/3.10/lib/python/site-packages (0.4.3)\r\nRequirement already satisfied: msgpack>=0.5.0 in ./Library/Python/3.10/lib/python/site-packages (from pynvim) (1.0.3)\r\nRequirement already satisfied: greenlet in ./Library/Python/3.10/lib/python/site-packages (from pynvim) (1.1.2)",
            "created_at": "2022-01-23T02:51:10Z",
            "html_url": "https://github.com/neovim/neovim/issues/17172#issuecomment-1019401167",
            "id": 1019401167,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/17172",
            "node_id": "IC_kwDOAPphoM48wtPP",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1019401167/reactions"
            },
            "updated_at": "2022-01-23T02:51:10Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1019401167",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/271288?v=4",
                "events_url": "https://api.github.com/users/jeffschwartz/events{/privacy}",
                "followers_url": "https://api.github.com/users/jeffschwartz/followers",
                "following_url": "https://api.github.com/users/jeffschwartz/following{/other_user}",
                "gists_url": "https://api.github.com/users/jeffschwartz/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/jeffschwartz",
                "id": 271288,
                "login": "jeffschwartz",
                "node_id": "MDQ6VXNlcjI3MTI4OA==",
                "organizations_url": "https://api.github.com/users/jeffschwartz/orgs",
                "received_events_url": "https://api.github.com/users/jeffschwartz/received_events",
                "repos_url": "https://api.github.com/users/jeffschwartz/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/jeffschwartz/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/jeffschwartz/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/jeffschwartz"
            }
        },
        {
            "author_association": "NONE",
            "body": "Hi yes I’m sorry I haven’t gotten back to this but I have a lot todo and no\nhelp. But I will get to it as soon as I can. I’m still really new at all of\nthis and my buisness is on a level I have no idea about but I’m working 18\nto 14 hours a day to stay in compliance and regulation. But it is only me\nand I am disabled plus’s only one person so can I get GitHub to help my\ndevelopment please y’all have been so good to me and I love y’all but I\nhave worked three years for my company and I haven’t paid myself nor gotten\na break from anything thanks\n\nOn Sat, Jan 22, 2022 at 20:02 Jeff Schwartz ***@***.***>\nwrote:\n\n> Neovim version (nvim -v)\n>\n> 0.6.1\n> Vim (not Nvim) behaves the same?\n>\n> n/a\n> Operating system/version\n>\n> mac os 11.6.2\n> Terminal name/version\n>\n> iTerm2\n> $TERM environment variable\n>\n> xterm-256color\n> Installation\n>\n> brew install neovim\n> How to reproduce the issue\n>\n> :checkhealth provider results in\n> Python 3 provider (optional)\n>\n>    - INFO: Using: g:python3_host_prog = \"/usr/local/bin/python3.9\"\n>    - WARNING: No Python executable found that can import neovim. Using\n>    the first available executable for diagnostics.\n>    - INFO: Executable: Not found\n>\n> Expected behavior\n>\n> To find my installed python3:\n>\n> ➜ ~ which python3\n> /Library/Frameworks/Python.framework/Versions/3.10/bin/python3\n>\n> ➜ ~ file /Library/Frameworks/Python.framework/Versions/3.10/bin/python3\n> /Library/Frameworks/Python.framework/Versions/3.10/bin/python3: Mach-O\n> universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable\n> x86_64] [arm64:Mach-O 64-bit executable arm64]\n> /Library/Frameworks/Python.framework/Versions/3.10/bin/python3 (for\n> architecture x86_64):Mach-O 64-bit executable x86_64\n> /Library/Frameworks/Python.framework/Versions/3.10/bin/python3 (for\n> architecture arm64): Mach-O 64-bit executable arm64\n> Actual behavior\n>\n> :checkhealth provider results in\n> Python 3 provider (optional)\n>\n>    - INFO: Using: g:python3_host_prog = \"/usr/local/bin/python3.9\"\n>    - WARNING: No Python executable found that can import neovim. Using\n>    the first available executable for diagnostics.\n>    - INFO: Executable: Not found\n>\n> —\n> Reply to this email directly, view it on GitHub\n> <https://github.com/neovim/neovim/issues/17172>, or unsubscribe\n> <https://github.com/notifications/unsubscribe-auth/ASBW4VXIR33OPSM4ZE4IDV3UXNOUZANCNFSM5MSXBBIA>\n> .\n> You are receiving this because you are subscribed to this thread.Message\n> ID: ***@***.***>\n>\n",
            "created_at": "2022-01-23T04:10:26Z",
            "html_url": "https://github.com/neovim/neovim/issues/17172#issuecomment-1019410471",
            "id": 1019410471,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/17172",
            "node_id": "IC_kwDOAPphoM48wvgn",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1019410471/reactions"
            },
            "updated_at": "2022-01-23T04:10:26Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1019410471",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/75722326?v=4",
                "events_url": "https://api.github.com/users/Mcculloughj/events{/privacy}",
                "followers_url": "https://api.github.com/users/Mcculloughj/followers",
                "following_url": "https://api.github.com/users/Mcculloughj/following{/other_user}",
                "gists_url": "https://api.github.com/users/Mcculloughj/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/Mcculloughj",
                "id": 75722326,
                "login": "Mcculloughj",
                "node_id": "MDQ6VXNlcjc1NzIyMzI2",
                "organizations_url": "https://api.github.com/users/Mcculloughj/orgs",
                "received_events_url": "https://api.github.com/users/Mcculloughj/received_events",
                "repos_url": "https://api.github.com/users/Mcculloughj/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/Mcculloughj/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/Mcculloughj/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/Mcculloughj"
            }
        },
        {
            "author_association": "NONE",
            "body": "I'm also experiencing permission denied for tree-sitter (see image below) when I start nvim but not sure if this is related to my op. FYI I installed neovim using Homebrew.\r\n\r\n<img width=\"1507\" alt=\"Screen Shot 2022-01-23 at 2 33 45 PM\" src=\"https://user-images.githubusercontent.com/271288/150695189-e156424a-cd17-4bb5-930a-6acea58342c4.png\">\r\n\r\nThis is no longer an issue - see https://github.com/neovim/neovim/issues/17172#issuecomment-1020227169 below.",
            "created_at": "2022-01-23T19:41:53Z",
            "html_url": "https://github.com/neovim/neovim/issues/17172#issuecomment-1019553408",
            "id": 1019553408,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/17172",
            "node_id": "IC_kwDOAPphoM48xSaA",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1019553408/reactions"
            },
            "updated_at": "2022-01-24T15:35:33Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1019553408",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/271288?v=4",
                "events_url": "https://api.github.com/users/jeffschwartz/events{/privacy}",
                "followers_url": "https://api.github.com/users/jeffschwartz/followers",
                "following_url": "https://api.github.com/users/jeffschwartz/following{/other_user}",
                "gists_url": "https://api.github.com/users/jeffschwartz/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/jeffschwartz",
                "id": 271288,
                "login": "jeffschwartz",
                "node_id": "MDQ6VXNlcjI3MTI4OA==",
                "organizations_url": "https://api.github.com/users/jeffschwartz/orgs",
                "received_events_url": "https://api.github.com/users/jeffschwartz/received_events",
                "repos_url": "https://api.github.com/users/jeffschwartz/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/jeffschwartz/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/jeffschwartz/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/jeffschwartz"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "Does this happen with `nvim -u NORC`? I don't see why neovim would pick up python 3.9 ( `Using: g:python3_host_prog = \"/usr/local/bin/python3.9\"` ) if 3.10 is first in your $PATH ( `which python3 = /Library/Frameworks/Python.framework/Versions/3.10/bin/python3` ).\r\nDoes adding `let g:python3_host_prog = \"/Library/Frameworks/Python.framework/Versions/3.10/bin/python3` at the end of your init.vim fix the problem?",
            "created_at": "2022-01-24T14:26:24Z",
            "html_url": "https://github.com/neovim/neovim/issues/17172#issuecomment-1020156119",
            "id": 1020156119,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/17172",
            "node_id": "IC_kwDOAPphoM48zljX",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1020156119/reactions"
            },
            "updated_at": "2022-01-24T14:27:21Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1020156119",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/11534587?v=4",
                "events_url": "https://api.github.com/users/glacambre/events{/privacy}",
                "followers_url": "https://api.github.com/users/glacambre/followers",
                "following_url": "https://api.github.com/users/glacambre/following{/other_user}",
                "gists_url": "https://api.github.com/users/glacambre/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/glacambre",
                "id": 11534587,
                "login": "glacambre",
                "node_id": "MDQ6VXNlcjExNTM0NTg3",
                "organizations_url": "https://api.github.com/users/glacambre/orgs",
                "received_events_url": "https://api.github.com/users/glacambre/received_events",
                "repos_url": "https://api.github.com/users/glacambre/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/glacambre/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/glacambre/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/glacambre"
            }
        },
        {
            "author_association": "NONE",
            "body": "@glacambre I found the problem. I had been using both Homebrew and Macports and found that the two package managers do not coexist very well, specifically in their path requirements. I have uninstalled Macports and I am currently in the process of reinstalling my environment using only Homebrew. Once that is done I will close this issue out once I have Neovim working on my Mac M1. Sorry that I burdened all with this but I didn't know that using the 2 package managers would cause a problem.",
            "created_at": "2022-01-24T14:33:51Z",
            "html_url": "https://github.com/neovim/neovim/issues/17172#issuecomment-1020163604",
            "id": 1020163604,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/17172",
            "node_id": "IC_kwDOAPphoM48znYU",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1020163604/reactions"
            },
            "updated_at": "2022-01-24T14:33:51Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1020163604",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/271288?v=4",
                "events_url": "https://api.github.com/users/jeffschwartz/events{/privacy}",
                "followers_url": "https://api.github.com/users/jeffschwartz/followers",
                "following_url": "https://api.github.com/users/jeffschwartz/following{/other_user}",
                "gists_url": "https://api.github.com/users/jeffschwartz/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/jeffschwartz",
                "id": 271288,
                "login": "jeffschwartz",
                "node_id": "MDQ6VXNlcjI3MTI4OA==",
                "organizations_url": "https://api.github.com/users/jeffschwartz/orgs",
                "received_events_url": "https://api.github.com/users/jeffschwartz/received_events",
                "repos_url": "https://api.github.com/users/jeffschwartz/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/jeffschwartz/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/jeffschwartz/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/jeffschwartz"
            }
        },
        {
            "author_association": "NONE",
            "body": "@zeertzjq  @glacambre \r\n\r\nI removed Macports and reset my .zprofile to default and this eliminated the permission denied issues (see above). I now get no errors when starting nvim. However, I am now still getting the E319: No \"python3\" provider found. Run \":checkhealth provider\".\r\n\r\n<img width=\"1106\" alt=\"Screen Shot 2022-01-24 at 10 23 57 AM\" src=\"https://user-images.githubusercontent.com/271288/150811649-33dbc730-8b4b-4996-8b90-00706801a5af.png\">\r\n\r\nAs stated, my paths are now correct so python3 should have been found:\r\n\r\n<img width=\"1482\" alt=\"Screen Shot 2022-01-24 at 10 27 37 AM\" src=\"https://user-images.githubusercontent.com/271288/150812502-be60d510-ec1e-4029-a550-54dd493d94e8.png\">\r\n\r\n<img width=\"1602\" alt=\"Screen Shot 2022-01-24 at 10 29 56 AM\" src=\"https://user-images.githubusercontent.com/271288/150812716-5b5a4f2a-0d79-47ff-b884-78871964f795.png\">\r\n\r\nI checked if pynvim is installed;\r\n\r\n<img width=\"1438\" alt=\"Screen Shot 2022-01-24 at 10 42 08 AM\" src=\"https://user-images.githubusercontent.com/271288/150815106-ca1dcb4f-61e6-4488-aead-6dfbb7e443ce.png\">\r\n\r\nI also aliased python to python3:\r\n\r\n<img width=\"948\" alt=\"Screen Shot 2022-01-24 at 10 31 51 AM\" src=\"https://user-images.githubusercontent.com/271288/150813002-02391378-5350-4b0d-b419-f23a89adad7a.png\">\r\n\r\nSo presumably python is discoverable now yet nvim plugins cannot.\r\n",
            "created_at": "2022-01-24T15:33:47Z",
            "html_url": "https://github.com/neovim/neovim/issues/17172#issuecomment-1020227169",
            "id": 1020227169,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/17172",
            "node_id": "IC_kwDOAPphoM48z25h",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1020227169/reactions"
            },
            "updated_at": "2022-01-24T15:44:17Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1020227169",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/271288?v=4",
                "events_url": "https://api.github.com/users/jeffschwartz/events{/privacy}",
                "followers_url": "https://api.github.com/users/jeffschwartz/followers",
                "following_url": "https://api.github.com/users/jeffschwartz/following{/other_user}",
                "gists_url": "https://api.github.com/users/jeffschwartz/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/jeffschwartz",
                "id": 271288,
                "login": "jeffschwartz",
                "node_id": "MDQ6VXNlcjI3MTI4OA==",
                "organizations_url": "https://api.github.com/users/jeffschwartz/orgs",
                "received_events_url": "https://api.github.com/users/jeffschwartz/received_events",
                "repos_url": "https://api.github.com/users/jeffschwartz/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/jeffschwartz/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/jeffschwartz/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/jeffschwartz"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "Did you (re)install `pynvim` _for this Python version_? (Your [comment above](https://github.com/neovim/neovim/issues/17172#issuecomment-1019401167) refers to Python 3.10, while the Homebrew version in your screenshot is Python 3.9.)",
            "created_at": "2022-01-24T15:36:01Z",
            "html_url": "https://github.com/neovim/neovim/issues/17172#issuecomment-1020229384",
            "id": 1020229384,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/17172",
            "node_id": "IC_kwDOAPphoM48z3cI",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1020229384/reactions"
            },
            "updated_at": "2022-01-24T16:25:08Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1020229384",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/2361214?v=4",
                "events_url": "https://api.github.com/users/clason/events{/privacy}",
                "followers_url": "https://api.github.com/users/clason/followers",
                "following_url": "https://api.github.com/users/clason/following{/other_user}",
                "gists_url": "https://api.github.com/users/clason/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/clason",
                "id": 2361214,
                "login": "clason",
                "node_id": "MDQ6VXNlcjIzNjEyMTQ=",
                "organizations_url": "https://api.github.com/users/clason/orgs",
                "received_events_url": "https://api.github.com/users/clason/received_events",
                "repos_url": "https://api.github.com/users/clason/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/clason/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/clason/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/clason"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "@jeffschwartz My questions still stand :) :\r\n- Does this happen with `nvim -u NORC`?\r\n- Does adding `let g:python3_host_prog = \"~/Library/Frameworks/Python.framework/Versions/3.10/bin/python3\"` at the end of your init.vim fix the problem?\r\n- Additionally, does adding `export PYTHONPATH=\"~/Library/Python/3.9/lib/python/site-packages:$PYTHONPATH\"` to your .zshrc fix the problem?",
            "created_at": "2022-01-24T16:23:23Z",
            "html_url": "https://github.com/neovim/neovim/issues/17172#issuecomment-1020281281",
            "id": 1020281281,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/17172",
            "node_id": "IC_kwDOAPphoM480EHB",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 2,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 2,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1020281281/reactions"
            },
            "updated_at": "2022-01-24T16:23:23Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1020281281",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/11534587?v=4",
                "events_url": "https://api.github.com/users/glacambre/events{/privacy}",
                "followers_url": "https://api.github.com/users/glacambre/followers",
                "following_url": "https://api.github.com/users/glacambre/following{/other_user}",
                "gists_url": "https://api.github.com/users/glacambre/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/glacambre",
                "id": 11534587,
                "login": "glacambre",
                "node_id": "MDQ6VXNlcjExNTM0NTg3",
                "organizations_url": "https://api.github.com/users/glacambre/orgs",
                "received_events_url": "https://api.github.com/users/glacambre/received_events",
                "repos_url": "https://api.github.com/users/glacambre/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/glacambre/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/glacambre/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/glacambre"
            }
        },
        {
            "author_association": "NONE",
            "body": "@clason \r\n<img width=\"490\" alt=\"Screen Shot 2022-01-24 at 11 50 43 AM\" src=\"https://user-images.githubusercontent.com/271288/150827895-546e75d6-d637-415f-89d6-55eb6bf34f69.png\">\r\n",
            "created_at": "2022-01-24T16:54:08Z",
            "html_url": "https://github.com/neovim/neovim/issues/17172#issuecomment-1020312830",
            "id": 1020312830,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/17172",
            "node_id": "IC_kwDOAPphoM480Lz-",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1020312830/reactions"
            },
            "updated_at": "2022-01-24T16:54:37Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1020312830",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/271288?v=4",
                "events_url": "https://api.github.com/users/jeffschwartz/events{/privacy}",
                "followers_url": "https://api.github.com/users/jeffschwartz/followers",
                "following_url": "https://api.github.com/users/jeffschwartz/following{/other_user}",
                "gists_url": "https://api.github.com/users/jeffschwartz/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/jeffschwartz",
                "id": 271288,
                "login": "jeffschwartz",
                "node_id": "MDQ6VXNlcjI3MTI4OA==",
                "organizations_url": "https://api.github.com/users/jeffschwartz/orgs",
                "received_events_url": "https://api.github.com/users/jeffschwartz/received_events",
                "repos_url": "https://api.github.com/users/jeffschwartz/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/jeffschwartz/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/jeffschwartz/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/jeffschwartz"
            }
        },
        {
            "author_association": "NONE",
            "body": "@clason \r\nThank you for assistance. I really appreciate it. Everything works now as it should. You have been a great help! I am closing out this issue now.",
            "created_at": "2022-01-24T17:41:12Z",
            "html_url": "https://github.com/neovim/neovim/issues/17172#issuecomment-1020366965",
            "id": 1020366965,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/17172",
            "node_id": "IC_kwDOAPphoM480ZB1",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 1,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 1,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1020366965/reactions"
            },
            "updated_at": "2022-01-24T17:41:12Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1020366965",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/271288?v=4",
                "events_url": "https://api.github.com/users/jeffschwartz/events{/privacy}",
                "followers_url": "https://api.github.com/users/jeffschwartz/followers",
                "following_url": "https://api.github.com/users/jeffschwartz/following{/other_user}",
                "gists_url": "https://api.github.com/users/jeffschwartz/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/jeffschwartz",
                "id": 271288,
                "login": "jeffschwartz",
                "node_id": "MDQ6VXNlcjI3MTI4OA==",
                "organizations_url": "https://api.github.com/users/jeffschwartz/orgs",
                "received_events_url": "https://api.github.com/users/jeffschwartz/received_events",
                "repos_url": "https://api.github.com/users/jeffschwartz/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/jeffschwartz/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/jeffschwartz/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/jeffschwartz"
            }
        },
        {
            "author_association": "NONE",
            "body": "It appears that installing **Python3 via Winget** may be causing some issues. I do not wish to replicate the problem here, but I wanted to bring it to your attention. I **recommend using the official installer** and restarting your system to resolve any potential issues.\r\n\r\nI assume something is wrong with the file permissions.",
            "created_at": "2023-07-26T15:46:16Z",
            "html_url": "https://github.com/neovim/neovim/issues/17172#issuecomment-1652081313",
            "id": 1652081313,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/17172",
            "node_id": "IC_kwDOAPphoM5ieMKh",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1652081313/reactions"
            },
            "updated_at": "2023-07-26T15:48:08Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1652081313",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/53002741?v=4",
                "events_url": "https://api.github.com/users/Endermanbugzjfc/events{/privacy}",
                "followers_url": "https://api.github.com/users/Endermanbugzjfc/followers",
                "following_url": "https://api.github.com/users/Endermanbugzjfc/following{/other_user}",
                "gists_url": "https://api.github.com/users/Endermanbugzjfc/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/Endermanbugzjfc",
                "id": 53002741,
                "login": "Endermanbugzjfc",
                "node_id": "MDQ6VXNlcjUzMDAyNzQx",
                "organizations_url": "https://api.github.com/users/Endermanbugzjfc/orgs",
                "received_events_url": "https://api.github.com/users/Endermanbugzjfc/received_events",
                "repos_url": "https://api.github.com/users/Endermanbugzjfc/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/Endermanbugzjfc/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/Endermanbugzjfc/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/Endermanbugzjfc"
            }
        }
    ],
    "comments": 12,
    "comments_url": "https://api.github.com/repos/neovim/neovim/issues/17172/comments",
    "created_at": "2022-01-23T02:01:50Z",
    "events_url": "https://api.github.com/repos/neovim/neovim/issues/17172/events",
    "html_url": "https://github.com/neovim/neovim/issues/17172",
    "id": 1111746831,
    "labels": [],
    "labels_url": "https://api.github.com/repos/neovim/neovim/issues/17172/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "I_kwDOAPphoM5CQ-kP",
    "number": 17172,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 0,
        "url": "https://api.github.com/repos/neovim/neovim/issues/17172/reactions"
    },
    "repository_url": "https://api.github.com/repos/neovim/neovim",
    "state": "closed",
    "state_reason": "completed",
    "timeline_url": "https://api.github.com/repos/neovim/neovim/issues/17172/timeline",
    "title": "No Python executable found that can `import neovim`",
    "updated_at": "2023-07-26T15:48:08Z",
    "url": "https://api.github.com/repos/neovim/neovim/issues/17172",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/271288?v=4",
        "events_url": "https://api.github.com/users/jeffschwartz/events{/privacy}",
        "followers_url": "https://api.github.com/users/jeffschwartz/followers",
        "following_url": "https://api.github.com/users/jeffschwartz/following{/other_user}",
        "gists_url": "https://api.github.com/users/jeffschwartz/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/jeffschwartz",
        "id": 271288,
        "login": "jeffschwartz",
        "node_id": "MDQ6VXNlcjI3MTI4OA==",
        "organizations_url": "https://api.github.com/users/jeffschwartz/orgs",
        "received_events_url": "https://api.github.com/users/jeffschwartz/received_events",
        "repos_url": "https://api.github.com/users/jeffschwartz/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/jeffschwartz/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/jeffschwartz/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/jeffschwartz"
    }
}