{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "MEMBER",
    "body": "### Problem\n\n:call nvim_cmd({'cmd': 'throw', 'args': ['42']}, {})\n\n### Steps to reproduce\n\n1. Run `nvim --clean`\r\n2. Run `:call nvim_cmd({'cmd': 'throw', 'args': ['42']}, {})`\r\n3. Crash\r\n```\r\n**/src/nvim/ex_eval.c:1841:22: runtime error: member access within null pointer of type 'cstack_T'\r\n    #0 0x5614692442df in cleanup_conditionals **/src/nvim/ex_eval.c:1841:22\r\n    #1 0x561469239373 in do_throw **/src/nvim/ex_eval.c:1184:13\r\n    #2 0x561469249589 in ex_throw **/src/nvim/ex_eval.c:1152:7\r\n    #3 0x5614691e8eae in execute_cmd0 **/src/nvim/ex_docmd.c:1634:7\r\n    #4 0x5614691e5062 in execute_cmd **/src/nvim/ex_docmd.c:1712:3\r\n    #5 0x5614689c51b9 in nvim_cmd **/src/nvim/api/command.c:707:3\r\n    #6 0x561468a81776 in handle_nvim_cmd **/build/src/nvim/auto/api/private/dispatch_wrappers.generated.h:2941:15\r\n    #7 0x56146900f65d in api_wrapper **/src/nvim/eval/funcs.c:349:19\r\n    #8 0x561468fbddba in call_internal_func **/src/nvim/eval/funcs.c:269:3\r\n    #9 0x5614690c55f2 in call_func **/src/nvim/eval/userfunc.c:1718:15\r\n    #10 0x5614690c1acd in get_func_tv **/src/nvim/eval/userfunc.c:556:11\r\n    #11 0x5614690fb9ea in ex_call_inner **/src/nvim/eval/userfunc.c:3159:9\r\n    #12 0x5614690f9aff in ex_call **/src/nvim/eval/userfunc.c:3395:14\r\n    #13 0x5614691e8eae in execute_cmd0 **/src/nvim/ex_docmd.c:1634:7\r\n    #14 0x5614691c5ea8 in do_one_cmd **/src/nvim/ex_docmd.c:2293:7\r\n    #15 0x5614691b673d in do_cmdline **/src/nvim/ex_docmd.c:592:20\r\n    #16 0x5614697e5b11 in nv_colon **/src/nvim/normal.c:3244:18\r\n    #17 0x5614697d0e5e in normal_execute **/src/nvim/normal.c:1202:3\r\n    #18 0x561469dd364c in state_enter **/src/nvim/state.c:99:26\r\n    #19 0x5614697b416e in normal_enter **/src/nvim/normal.c:501:3\r\n    #20 0x56146890cf5d in main **/src/nvim/main.c:647:3\r\n    #21 0x7ff316e23ccf  (/usr/lib/libc.so.6+0x23ccf) (BuildId: cff743d3e7895fef5f86ed27cdf25c1b8ce21a1d)\r\n    #22 0x7ff316e23d89 in __libc_start_main (/usr/lib/libc.so.6+0x23d89) (BuildId: cff743d3e7895fef5f86ed27cdf25c1b8ce21a1d)\r\n    #23 0x56146880bd64 in _start (**/build/bin/nvim+0xba8d64) (BuildId: e96b87d742b8b7af294a015a4515e5a4774706dd)\r\n\r\nSUMMARY: UndefinedBehaviorSanitizer: undefined-behavior **/src/nvim/ex_eval.c:1841:22 in \r\n```\n\n### Expected behavior\n\nNo crash\n\n### Neovim version (nvim -v)\n\nv0.10.0-dev-761+g3d3ec27d5\n\n### Vim (not Nvim) behaves the same?\n\nN/A\n\n### Operating system/version\n\nArch Linux\n\n### Terminal name/version\n\nkitty 0.29.2\n\n### $TERM environment variable\n\nxterm-kitty\n\n### Installation\n\nbuild from repo",
    "closed_at": "2023-12-01T05:56:06Z",
    "comment_data": [
        {
            "author_association": "MEMBER",
            "body": "The following change seems to fix the crash:\r\n```diff\r\ndiff --git a/src/nvim/ex_docmd.c b/src/nvim/ex_docmd.c\r\nindex f154b5b77..3fad91353 100644\r\n--- a/src/nvim/ex_docmd.c\r\n+++ b/src/nvim/ex_docmd.c\r\n@@ -1708,6 +1708,9 @@ int execute_cmd(exarg_T *eap, CmdParseInfo *cmdinfo, bool preview)\r\n     goto end;\r\n   }\r\n \r\n+  cstack_T cstack = { .cs_idx = -1 };\r\n+  eap->cstack = &cstack;\r\n+\r\n   // Execute the command\r\n   execute_cmd0(&retv, eap, &errormsg, preview);\r\n \r\n```\r\nBut it seems that more code may be needed after `execute_cmd0()`.",
            "created_at": "2023-08-04T06:41:35Z",
            "html_url": "https://github.com/neovim/neovim/issues/24556#issuecomment-1665091472",
            "id": 1665091472,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/24556",
            "node_id": "IC_kwDOAPphoM5jP0eQ",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1665091472/reactions"
            },
            "updated_at": "2023-08-04T06:41:35Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1665091472",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/35768171?v=4",
                "events_url": "https://api.github.com/users/zeertzjq/events{/privacy}",
                "followers_url": "https://api.github.com/users/zeertzjq/followers",
                "following_url": "https://api.github.com/users/zeertzjq/following{/other_user}",
                "gists_url": "https://api.github.com/users/zeertzjq/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/zeertzjq",
                "id": 35768171,
                "login": "zeertzjq",
                "node_id": "MDQ6VXNlcjM1NzY4MTcx",
                "organizations_url": "https://api.github.com/users/zeertzjq/orgs",
                "received_events_url": "https://api.github.com/users/zeertzjq/received_events",
                "repos_url": "https://api.github.com/users/zeertzjq/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/zeertzjq/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/zeertzjq/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/zeertzjq"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "The same crash also applies to `:return` when there is an outer function:\r\n```vim\r\nfunc Foo()\r\n  echo 23\r\n  call nvim_cmd({'cmd': 'return'}, {})\r\n  echo 45\r\nendfunc\r\n\r\ncall Foo()\r\n```\r\n\r\nThe fix above seems to work as well.",
            "created_at": "2023-08-04T06:55:06Z",
            "html_url": "https://github.com/neovim/neovim/issues/24556#issuecomment-1665103702",
            "id": 1665103702,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/24556",
            "node_id": "IC_kwDOAPphoM5jP3dW",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1665103702/reactions"
            },
            "updated_at": "2023-08-04T06:55:27Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1665103702",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/35768171?v=4",
                "events_url": "https://api.github.com/users/zeertzjq/events{/privacy}",
                "followers_url": "https://api.github.com/users/zeertzjq/followers",
                "following_url": "https://api.github.com/users/zeertzjq/following{/other_user}",
                "gists_url": "https://api.github.com/users/zeertzjq/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/zeertzjq",
                "id": 35768171,
                "login": "zeertzjq",
                "node_id": "MDQ6VXNlcjM1NzY4MTcx",
                "organizations_url": "https://api.github.com/users/zeertzjq/orgs",
                "received_events_url": "https://api.github.com/users/zeertzjq/received_events",
                "repos_url": "https://api.github.com/users/zeertzjq/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/zeertzjq/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/zeertzjq/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/zeertzjq"
            }
        },
        {
            "author_association": "NONE",
            "body": "The same crash happens from lua\r\n```lua \r\nvim.cmd.throw(42)\r\n```\r\n\r\nThanks @zeertzjq ",
            "created_at": "2023-08-04T14:25:52Z",
            "html_url": "https://github.com/neovim/neovim/issues/24556#issuecomment-1665702342",
            "id": 1665702342,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/24556",
            "node_id": "IC_kwDOAPphoM5jSJnG",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1665702342/reactions"
            },
            "updated_at": "2023-08-04T14:52:46Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1665702342",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/1560508?v=4",
                "events_url": "https://api.github.com/users/ryoppippi/events{/privacy}",
                "followers_url": "https://api.github.com/users/ryoppippi/followers",
                "following_url": "https://api.github.com/users/ryoppippi/following{/other_user}",
                "gists_url": "https://api.github.com/users/ryoppippi/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/ryoppippi",
                "id": 1560508,
                "login": "ryoppippi",
                "node_id": "MDQ6VXNlcjE1NjA1MDg=",
                "organizations_url": "https://api.github.com/users/ryoppippi/orgs",
                "received_events_url": "https://api.github.com/users/ryoppippi/received_events",
                "repos_url": "https://api.github.com/users/ryoppippi/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/ryoppippi/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/ryoppippi/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/ryoppippi"
            }
        }
    ],
    "comments": 3,
    "comments_url": "https://api.github.com/repos/neovim/neovim/issues/24556/comments",
    "created_at": "2023-08-04T06:37:58Z",
    "events_url": "https://api.github.com/repos/neovim/neovim/issues/24556/events",
    "html_url": "https://github.com/neovim/neovim/issues/24556",
    "id": 1836158143,
    "labels": [
        {
            "color": "c5def5",
            "default": false,
            "description": "libnvim, Nvim RPC API",
            "id": 103819671,
            "name": "api",
            "node_id": "MDU6TGFiZWwxMDM4MTk2NzE=",
            "url": "https://api.github.com/repos/neovim/neovim/labels/api"
        },
        {
            "color": "c7def8",
            "default": false,
            "description": "",
            "id": 109899557,
            "name": "vimscript",
            "node_id": "MDU6TGFiZWwxMDk4OTk1NTc=",
            "url": "https://api.github.com/repos/neovim/neovim/labels/vimscript"
        },
        {
            "color": "0E8A16",
            "default": false,
            "description": "issue contains a stacktrace/ASAN log",
            "id": 435854079,
            "name": "has:backtrace",
            "node_id": "MDU6TGFiZWw0MzU4NTQwNzk=",
            "url": "https://api.github.com/repos/neovim/neovim/labels/has:backtrace"
        },
        {
            "color": "F9D0C4",
            "default": false,
            "description": "issue reporting a crash or segfault",
            "id": 435854234,
            "name": "bug-crash",
            "node_id": "MDU6TGFiZWw0MzU4NTQyMzQ=",
            "url": "https://api.github.com/repos/neovim/neovim/labels/bug-crash"
        }
    ],
    "labels_url": "https://api.github.com/repos/neovim/neovim/issues/24556/labels{/name}",
    "locked": false,
    "milestone": {
        "closed_at": null,
        "closed_issues": 30,
        "created_at": "2023-10-09T10:31:49Z",
        "creator": {
            "avatar_url": "https://avatars.githubusercontent.com/u/35768171?v=4",
            "events_url": "https://api.github.com/users/zeertzjq/events{/privacy}",
            "followers_url": "https://api.github.com/users/zeertzjq/followers",
            "following_url": "https://api.github.com/users/zeertzjq/following{/other_user}",
            "gists_url": "https://api.github.com/users/zeertzjq/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/zeertzjq",
            "id": 35768171,
            "login": "zeertzjq",
            "node_id": "MDQ6VXNlcjM1NzY4MTcx",
            "organizations_url": "https://api.github.com/users/zeertzjq/orgs",
            "received_events_url": "https://api.github.com/users/zeertzjq/received_events",
            "repos_url": "https://api.github.com/users/zeertzjq/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/zeertzjq/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/zeertzjq/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/zeertzjq"
        },
        "description": "",
        "due_on": null,
        "html_url": "https://github.com/neovim/neovim/milestone/40",
        "id": 10019067,
        "labels_url": "https://api.github.com/repos/neovim/neovim/milestones/40/labels",
        "node_id": "MI_kwDOAPphoM4AmOD7",
        "number": 40,
        "open_issues": 8,
        "state": "open",
        "title": "0.9.5",
        "updated_at": "2023-12-01T05:56:44Z",
        "url": "https://api.github.com/repos/neovim/neovim/milestones/40"
    },
    "node_id": "I_kwDOAPphoM5tcYy_",
    "number": 24556,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 1,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 1,
        "url": "https://api.github.com/repos/neovim/neovim/issues/24556/reactions"
    },
    "repository_url": "https://api.github.com/repos/neovim/neovim",
    "state": "closed",
    "state_reason": "completed",
    "timeline_url": "https://api.github.com/repos/neovim/neovim/issues/24556/timeline",
    "title": "Crash when using `:throw` directly from `nvim_cmd`",
    "updated_at": "2023-12-01T05:56:39Z",
    "url": "https://api.github.com/repos/neovim/neovim/issues/24556",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/35768171?v=4",
        "events_url": "https://api.github.com/users/zeertzjq/events{/privacy}",
        "followers_url": "https://api.github.com/users/zeertzjq/followers",
        "following_url": "https://api.github.com/users/zeertzjq/following{/other_user}",
        "gists_url": "https://api.github.com/users/zeertzjq/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/zeertzjq",
        "id": 35768171,
        "login": "zeertzjq",
        "node_id": "MDQ6VXNlcjM1NzY4MTcx",
        "organizations_url": "https://api.github.com/users/zeertzjq/orgs",
        "received_events_url": "https://api.github.com/users/zeertzjq/received_events",
        "repos_url": "https://api.github.com/users/zeertzjq/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/zeertzjq/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/zeertzjq/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/zeertzjq"
    }
}