{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "NONE",
    "body": "### Problem\n\n**### Every time I open neovim I encounter this error message containing : E5113\r\nI use these plugins : treesitter, packer, telescope.**\r\n### \r\n\r\n\r\n_```\r\nError detected while processing /home/anes/.config/nvim/plugin/packer_compiled.lua:\r\nE5113: Error while calling lua chunk: /home/anes/.config/nvim/plugin/packer_compiled.lua:8: /home/anes/.config/nvim/plugin/packer_compi\r\nled.lua: Vim(packadd):E919: Directory not found in 'packpath': \"pack/*/opt/packer.nvim\"\r\nstack traceback:\r\n        [C]: in function 'nvim_command'\r\n        /home/anes/.config/nvim/plugin/packer_compiled.lua:8: in main chunk\r\nError detected while processing /home/anes/.config/nvim/after/plugin/telescope.lua:\r\nE5113: Error while calling lua chunk: /home/anes/.config/nvim/after/plugin/telescope.lua:1: module 'telescope.builtin' not found:\r\n        no field package.preload['telescope.builtin']\r\n        no file './telescope/builtin.lua'\r\n        no file '/usr/share/luajit-2.1.0-beta3/telescope/builtin.lua'\r\n        no file '/usr/local/share/lua/5.1/telescope/builtin.lua'\r\n        no file '/usr/local/share/lua/5.1/telescope/builtin/init.lua'\r\n        no file '/usr/share/lua/5.1/telescope/builtin.lua'\r\n        no file '/usr/share/lua/5.1/telescope/builtin/init.lua'\r\n        no file './telescope/builtin.so'\r\n        no file '/usr/local/lib/lua/5.1/telescope/builtin.so'\r\n        no file '/usr/lib/lua/5.1/telescope/builtin.so'\r\n        no file '/usr/local/lib/lua/5.1/loadall.so'\r\n        no file './telescope.so'\r\n        no file '/usr/local/lib/lua/5.1/telescope.so'\r\n        no file '/usr/lib/lua/5.1/telescope.so'\r\n        no file '/usr/local/lib/lua/5.1/loadall.so'\r\nstack traceback:\r\n        [C]: in function 'require'\r\n        /home/anes/.config/nvim/after/plugin/telescope.lua:1: in main chunk\r\n```_\r\n\n\n### Steps to reproduce\n\nnvim --clean\n\n### Expected behavior\n\nOpening as expected \n\n### Neovim version (nvim -v)\n\n0.9.1\n\n### Vim (not Nvim) behaves the same?\n\ndidn't try it\n\n### Operating system/version\n\nendeavour os \n\n### Terminal name/version\n\nkitty\n\n### $TERM environment variable\n\nxterm-256-color\n\n### Installation\n\npacman",
    "closed_at": "2023-08-18T00:31:28Z",
    "comment_data": [
        {
            "author_association": "MEMBER",
            "body": "It's likely that you didn't install packer properly.",
            "created_at": "2023-08-18T00:31:28Z",
            "html_url": "https://github.com/neovim/neovim/issues/24772#issuecomment-1683154850",
            "id": 1683154850,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/24772",
            "node_id": "IC_kwDOAPphoM5kUuei",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1683154850/reactions"
            },
            "updated_at": "2023-08-18T00:31:28Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1683154850",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/35768171?v=4",
                "events_url": "https://api.github.com/users/zeertzjq/events{/privacy}",
                "followers_url": "https://api.github.com/users/zeertzjq/followers",
                "following_url": "https://api.github.com/users/zeertzjq/following{/other_user}",
                "gists_url": "https://api.github.com/users/zeertzjq/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/zeertzjq",
                "id": 35768171,
                "login": "zeertzjq",
                "node_id": "MDQ6VXNlcjM1NzY4MTcx",
                "organizations_url": "https://api.github.com/users/zeertzjq/orgs",
                "received_events_url": "https://api.github.com/users/zeertzjq/received_events",
                "repos_url": "https://api.github.com/users/zeertzjq/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/zeertzjq/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/zeertzjq/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/zeertzjq"
            }
        }
    ],
    "comments": 1,
    "comments_url": "https://api.github.com/repos/neovim/neovim/issues/24772/comments",
    "created_at": "2023-08-18T00:10:21Z",
    "events_url": "https://api.github.com/repos/neovim/neovim/issues/24772/events",
    "html_url": "https://github.com/neovim/neovim/issues/24772",
    "id": 1855860788,
    "labels": [
        {
            "color": "e6e6e6",
            "default": false,
            "description": "Issues that are closed as \"invalid\"",
            "id": 77997477,
            "name": "closed:invalid",
            "node_id": "MDU6TGFiZWw3Nzk5NzQ3Nw==",
            "url": "https://api.github.com/repos/neovim/neovim/labels/closed:invalid"
        }
    ],
    "labels_url": "https://api.github.com/repos/neovim/neovim/issues/24772/labels{/name}",
    "locked": true,
    "milestone": null,
    "node_id": "I_kwDOAPphoM5unjA0",
    "number": 24772,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 0,
        "url": "https://api.github.com/repos/neovim/neovim/issues/24772/reactions"
    },
    "repository_url": "https://api.github.com/repos/neovim/neovim",
    "state": "closed",
    "state_reason": "not_planned",
    "timeline_url": "https://api.github.com/repos/neovim/neovim/issues/24772/timeline",
    "title": "Many erros while oppening neovim ",
    "updated_at": "2023-08-18T00:32:28Z",
    "url": "https://api.github.com/repos/neovim/neovim/issues/24772",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/142409542?v=4",
        "events_url": "https://api.github.com/users/dr34mbo4t/events{/privacy}",
        "followers_url": "https://api.github.com/users/dr34mbo4t/followers",
        "following_url": "https://api.github.com/users/dr34mbo4t/following{/other_user}",
        "gists_url": "https://api.github.com/users/dr34mbo4t/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/dr34mbo4t",
        "id": 142409542,
        "login": "dr34mbo4t",
        "node_id": "U_kgDOCHz_Rg",
        "organizations_url": "https://api.github.com/users/dr34mbo4t/orgs",
        "received_events_url": "https://api.github.com/users/dr34mbo4t/received_events",
        "repos_url": "https://api.github.com/users/dr34mbo4t/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/dr34mbo4t/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/dr34mbo4t/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/dr34mbo4t"
    }
}