{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "CONTRIBUTOR",
    "body": "### Problem\r\n\r\nI'm so sorry I don't have a repro, it randomly happened while I was doing a `yy`/`p` in a Neovim Lua functional test, and I don't know what I did to trigger it. I could table this and reopen at a later time when I have more details.\r\n\r\nThe line is here:\r\nhttps://github.com/neovim/neovim/blob/f67517bba30b6233bea85e1f6a8505171142d4ca/src/nvim/msgpack_rpc/unpacker.c#L467\r\n\r\n\r\n```\r\nThread 0 Crashed::  Dispatch queue: com.apple.main-thread\r\n0   libsystem_kernel.dylib        \t       0x1a81fc724 __pthread_kill + 8\r\n1   libsystem_pthread.dylib       \t       0x1a8233c28 pthread_kill + 288\r\n2   libsystem_c.dylib             \t       0x1a8141ae8 abort + 180\r\n3   libsystem_c.dylib             \t       0x1a8140e44 __assert_rtn + 272\r\n4   nvim                          \t       0x104613794 unpacker_parse_redraw + 1720 (unpacker.c:466)\r\n5   nvim                          \t       0x104612ddc unpacker_advance + 384 (unpacker.c:323)\r\n6   nvim                          \t       0x10460be58 parse_msgpack + 60 (channel.c:329)\r\n7   nvim                          \t       0x10460a680 receive_msgpack + 316 (channel.c:307)\r\n8   nvim                          \t       0x1044f79b4 read_event + 152 (rstream.c:192)\r\n9   nvim                          \t       0x1044f7770 invoke_read_cb + 208 (rstream.c:205)\r\n10  nvim                          \t       0x1044f74a4 read_cb + 376 (rstream.c:134)\r\n11  nvim                          \t       0x1048f76c8 uv__read + 1416 (stream.c:1143)\r\n12  nvim                          \t       0x1048f3700 uv__stream_io + 400 (stream.c:1203)\r\n13  nvim                          \t       0x1048ff4b4 uv__io_poll + 3460 (kqueue.c:381)\r\n14  nvim                          \t       0x1048df7d0 uv_run + 436 (core.c:447)\r\n15  nvim                          \t       0x1044f3b54 loop_uv_run + 200 (loop.c:65)\r\n16  nvim                          \t       0x1044f3c48 loop_poll_events + 44 (loop.c:87)\r\n17  nvim                          \t       0x1047854a8 ui_client_run + 176 (ui_client.c:125)\r\n18  nvim                          \t       0x104390674 main + 1992 (main.c:392)\r\n19  dyld                          \t       0x1a7edbf28 start + 2236\r\n```\r\n\r\n### Steps to reproduce\r\n\r\nN/A unfortunately \r\n\r\n### Expected behavior\r\n\r\nIDK how Neovim uses `assert`s but my assumption is that user/validation errors are caught, and `assert`s are always unintended?\r\n\r\n### Neovim version (nvim -v)\r\n\r\nbe10d65bf (0.10 nightly)\r\n\r\n### Vim (not Nvim) behaves the same?\r\n\r\nno\r\n\r\n### Operating system/version\r\n\r\nMacOS 13.4.1\r\n\r\n### Terminal name/version\r\n\r\nkitty 0.28.1\r\n\r\n### $TERM environment variable\r\n\r\nxterm-kitty\r\n\r\n### Installation\r\n\r\nbuild from repo",
    "closed_at": null,
    "comment_data": [],
    "comments": 0,
    "comments_url": "https://api.github.com/repos/neovim/neovim/issues/25184/comments",
    "created_at": "2023-09-16T05:09:36Z",
    "events_url": "https://api.github.com/repos/neovim/neovim/issues/25184/events",
    "html_url": "https://github.com/neovim/neovim/issues/25184",
    "id": 1899300479,
    "labels": [
        {
            "color": "c5def5",
            "default": false,
            "description": "",
            "id": 197254545,
            "name": "tui",
            "node_id": "MDU6TGFiZWwxOTcyNTQ1NDU=",
            "url": "https://api.github.com/repos/neovim/neovim/labels/tui"
        },
        {
            "color": "c7def8",
            "default": false,
            "description": null,
            "id": 242522707,
            "name": "rpc",
            "node_id": "MDU6TGFiZWwyNDI1MjI3MDc=",
            "url": "https://api.github.com/repos/neovim/neovim/labels/rpc"
        },
        {
            "color": "FBCA04",
            "default": false,
            "description": "We need minimal steps to reproduce the issue",
            "id": 298863445,
            "name": "needs:repro",
            "node_id": "MDU6TGFiZWwyOTg4NjM0NDU=",
            "url": "https://api.github.com/repos/neovim/neovim/labels/needs:repro"
        },
        {
            "color": "0E8A16",
            "default": false,
            "description": "issue contains a stacktrace/ASAN log",
            "id": 435854079,
            "name": "has:backtrace",
            "node_id": "MDU6TGFiZWw0MzU4NTQwNzk=",
            "url": "https://api.github.com/repos/neovim/neovim/labels/has:backtrace"
        },
        {
            "color": "F9D0C4",
            "default": false,
            "description": "issue reporting a crash or segfault",
            "id": 435854234,
            "name": "bug-crash",
            "node_id": "MDU6TGFiZWw0MzU4NTQyMzQ=",
            "url": "https://api.github.com/repos/neovim/neovim/labels/bug-crash"
        }
    ],
    "labels_url": "https://api.github.com/repos/neovim/neovim/issues/25184/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "I_kwDOAPphoM5xNQZ_",
    "number": 25184,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 1,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 1,
        "url": "https://api.github.com/repos/neovim/neovim/issues/25184/reactions"
    },
    "repository_url": "https://api.github.com/repos/neovim/neovim",
    "state": "open",
    "state_reason": null,
    "timeline_url": "https://api.github.com/repos/neovim/neovim/issues/25184/timeline",
    "title": "assertion failure at unpacker.c:466",
    "updated_at": "2023-10-06T06:32:40Z",
    "url": "https://api.github.com/repos/neovim/neovim/issues/25184",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/5601392?v=4",
        "events_url": "https://api.github.com/users/llllvvuu/events{/privacy}",
        "followers_url": "https://api.github.com/users/llllvvuu/followers",
        "following_url": "https://api.github.com/users/llllvvuu/following{/other_user}",
        "gists_url": "https://api.github.com/users/llllvvuu/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/llllvvuu",
        "id": 5601392,
        "login": "llllvvuu",
        "node_id": "MDQ6VXNlcjU2MDEzOTI=",
        "organizations_url": "https://api.github.com/users/llllvvuu/orgs",
        "received_events_url": "https://api.github.com/users/llllvvuu/received_events",
        "repos_url": "https://api.github.com/users/llllvvuu/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/llllvvuu/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/llllvvuu/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/llllvvuu"
    }
}