{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "NONE",
    "body": "### Problem\r\n\r\nHello neovim team, thanks so much for all your hard work!\r\n\r\nI lost a few hours trying to figure out why my lsp config wasn't being used. Turns out the init callback was throwing an error and neovim did not give any indication. \r\n\r\nI did some digging myself and found the problem. The `on_init` callback is called [here](https://github.com/neovim/neovim/blob/de9348978999aa78f8351b5f55930bb109e742f7/runtime/lua/vim/lsp.lua#L1441). There's a `pcall` and the error is ostensibly passed off to a handler via another `pcall`, but that handler doesn't seem to exist and the return value is dropped.\r\n\r\nUnfortunately, `pcall(nil)` doesn't throw and only returns `false, \"attempt to call a nil value\"`  so both errors are dropped and everyone is none the wiser. ðŸ˜± This is a good reminder that discarding the return of `pcall` is a _very bad_ idea. Too risky!\r\n\r\n\r\n### Steps to reproduce using \"nvim -u minimal_init.lua\"\r\n\r\n```lua\r\nlocal pattern = 'lua'\r\nlocal cmd = {'lua-language-server'}\r\n-- Add files/folders here that indicate the root of a project\r\nlocal root_markers = {'.git', '.editorconfig'}\r\n-- Change to table with settings if required\r\nlocal settings = vim.empty_dict()\r\n\r\nvim.api.nvim_create_autocmd('FileType', {\r\n  pattern = pattern,\r\n  callback = function(args)\r\n    local match = vim.fs.find(root_markers, { path = args.file, upward = true })[1]\r\n    local root_dir = match and vim.fn.fnamemodify(match, ':p:h') or nil\r\n    vim.lsp.start({\r\n      name = 'bugged-ls',\r\n      cmd = cmd,\r\n      root_dir = root_dir,\r\n      settings = settings,\r\n      on_init = function ()\r\n        print(\"INIT\")\r\n        error(\"whoops\")\r\n      end,\r\n      on_attach = function ()\r\n        print(\"ATTACH\")\r\n        error(\"my bad\")\r\n      end\r\n    })\r\n  end\r\n})\r\n```\r\n\r\n\r\n### Expected behavior\r\n\r\nneovim should indicate somehow that an error has occurred during the callback. \r\n\r\n### Neovim version (nvim -v)\r\n\r\nNVIM v0.10.0-dev-1203+g0592fd5e-dirty\r\n\r\n### Language server name/version\r\n\r\nlua-language-server 3.7.1\r\n\r\n### Operating system/version\r\n\r\nUbuntu 20\r\n\r\n### Log file\r\n\r\n_No response_",
    "closed_at": null,
    "comment_data": [
        {
            "author_association": "MEMBER",
            "body": "Falling back to `error()` or a `vim.notify()` if `handlers.on_error` doesn't exist seems reasonable. cc @mfussenegger.",
            "created_at": "2023-09-26T21:04:10Z",
            "html_url": "https://github.com/neovim/neovim/issues/25375#issuecomment-1736300079",
            "id": 1736300079,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/25375",
            "node_id": "IC_kwDOAPphoM5nfdYv",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1736300079/reactions"
            },
            "updated_at": "2023-09-26T21:04:10Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1736300079",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/8965202?v=4",
                "events_url": "https://api.github.com/users/gpanders/events{/privacy}",
                "followers_url": "https://api.github.com/users/gpanders/followers",
                "following_url": "https://api.github.com/users/gpanders/following{/other_user}",
                "gists_url": "https://api.github.com/users/gpanders/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/gpanders",
                "id": 8965202,
                "login": "gpanders",
                "node_id": "MDQ6VXNlcjg5NjUyMDI=",
                "organizations_url": "https://api.github.com/users/gpanders/orgs",
                "received_events_url": "https://api.github.com/users/gpanders/received_events",
                "repos_url": "https://api.github.com/users/gpanders/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/gpanders/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/gpanders/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/gpanders"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "I don't understand why [this line](https://github.com/neovim/neovim/blob/de9348978999aa78f8351b5f55930bb109e742f7/runtime/lua/vim/lsp.lua#L1443) is even using `handlers`, since those are supposed to be indexed by LSP method names. Instead it should be using `config.on_error`.\r\n\r\nI think it would be a good idea to move the implementation of [`dispatch.on_error`](https://github.com/neovim/neovim/blob/de9348978999aa78f8351b5f55930bb109e742f7/runtime/lua/vim/lsp.lua#L1183-L1193) to a separate shared function and use it as the error handler that's used during initialization.",
            "created_at": "2023-09-27T01:09:51Z",
            "html_url": "https://github.com/neovim/neovim/issues/25375#issuecomment-1736512925",
            "id": 1736512925,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/25375",
            "node_id": "IC_kwDOAPphoM5ngRWd",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1736512925/reactions"
            },
            "updated_at": "2023-09-27T01:09:51Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1736512925",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/62502207?v=4",
                "events_url": "https://api.github.com/users/MariaSolOs/events{/privacy}",
                "followers_url": "https://api.github.com/users/MariaSolOs/followers",
                "following_url": "https://api.github.com/users/MariaSolOs/following{/other_user}",
                "gists_url": "https://api.github.com/users/MariaSolOs/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/MariaSolOs",
                "id": 62502207,
                "login": "MariaSolOs",
                "node_id": "MDQ6VXNlcjYyNTAyMjA3",
                "organizations_url": "https://api.github.com/users/MariaSolOs/orgs",
                "received_events_url": "https://api.github.com/users/MariaSolOs/received_events",
                "repos_url": "https://api.github.com/users/MariaSolOs/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/MariaSolOs/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/MariaSolOs/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/MariaSolOs"
            }
        },
        {
            "author_association": "CONTRIBUTOR",
            "body": "In addition, there a few more places where errors are silently suppressed:\r\n\r\n(on_init): https://github.com/neovim/neovim/blob/de9348978999aa78f8351b5f55930bb109e742f7/runtime/lua/vim/lsp.lua#L1440-L1445\r\n(on_attach):\r\nhttps://github.com/neovim/neovim/blob/de9348978999aa78f8351b5f55930bb109e742f7/runtime/lua/vim/lsp.lua#L1716-L1719\r\n\r\nbefore_init: https://github.com/neovim/neovim/blob/de9348978999aa78f8351b5f55930bb109e742f7/runtime/lua/vim/lsp.lua#L1394-L1395\r\non_exit: https://github.com/neovim/neovim/blob/de9348978999aa78f8351b5f55930bb109e742f7/runtime/lua/vim/lsp.lua#L1223\r\n\r\nWe could have default error handlers (like a xpcall) which can show more stacktrace information via `vim.notify`.",
            "created_at": "2023-09-27T01:42:03Z",
            "html_url": "https://github.com/neovim/neovim/issues/25375#issuecomment-1736539224",
            "id": 1736539224,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/25375",
            "node_id": "IC_kwDOAPphoM5ngXxY",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1736539224/reactions"
            },
            "updated_at": "2023-09-27T01:44:56Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1736539224",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/1009873?v=4",
                "events_url": "https://api.github.com/users/wookayin/events{/privacy}",
                "followers_url": "https://api.github.com/users/wookayin/followers",
                "following_url": "https://api.github.com/users/wookayin/following{/other_user}",
                "gists_url": "https://api.github.com/users/wookayin/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/wookayin",
                "id": 1009873,
                "login": "wookayin",
                "node_id": "MDQ6VXNlcjEwMDk4NzM=",
                "organizations_url": "https://api.github.com/users/wookayin/orgs",
                "received_events_url": "https://api.github.com/users/wookayin/received_events",
                "repos_url": "https://api.github.com/users/wookayin/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/wookayin/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/wookayin/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/wookayin"
            }
        }
    ],
    "comments": 3,
    "comments_url": "https://api.github.com/repos/neovim/neovim/issues/25375/comments",
    "created_at": "2023-09-26T20:24:51Z",
    "events_url": "https://api.github.com/repos/neovim/neovim/issues/25375/events",
    "html_url": "https://github.com/neovim/neovim/issues/25375",
    "id": 1914246425,
    "labels": [
        {
            "color": "f9d0c4",
            "default": true,
            "description": "issues reporting wrong behavior",
            "id": 77997474,
            "name": "bug",
            "node_id": "MDU6TGFiZWw3Nzk5NzQ3NA==",
            "url": "https://api.github.com/repos/neovim/neovim/labels/bug"
        },
        {
            "color": "c5def5",
            "default": false,
            "description": null,
            "id": 662566370,
            "name": "lsp",
            "node_id": "MDU6TGFiZWw2NjI1NjYzNzA=",
            "url": "https://api.github.com/repos/neovim/neovim/labels/lsp"
        }
    ],
    "labels_url": "https://api.github.com/repos/neovim/neovim/issues/25375/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "I_kwDOAPphoM5yGRUZ",
    "number": 25375,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 0,
        "url": "https://api.github.com/repos/neovim/neovim/issues/25375/reactions"
    },
    "repository_url": "https://api.github.com/repos/neovim/neovim",
    "state": "open",
    "state_reason": null,
    "timeline_url": "https://api.github.com/repos/neovim/neovim/issues/25375/timeline",
    "title": "Errors in `on_init` and `on_attach` callbacks are not being reported to the user",
    "updated_at": "2023-09-27T01:44:56Z",
    "url": "https://api.github.com/repos/neovim/neovim/issues/25375",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/2105352?v=4",
        "events_url": "https://api.github.com/users/A-Babin/events{/privacy}",
        "followers_url": "https://api.github.com/users/A-Babin/followers",
        "following_url": "https://api.github.com/users/A-Babin/following{/other_user}",
        "gists_url": "https://api.github.com/users/A-Babin/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/A-Babin",
        "id": 2105352,
        "login": "A-Babin",
        "node_id": "MDQ6VXNlcjIxMDUzNTI=",
        "organizations_url": "https://api.github.com/users/A-Babin/orgs",
        "received_events_url": "https://api.github.com/users/A-Babin/received_events",
        "repos_url": "https://api.github.com/users/A-Babin/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/A-Babin/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/A-Babin/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/A-Babin"
    }
}