{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "NONE",
    "body": "### Problem\r\n\r\nReally strange error, and I just could not find anything online for solving that.\r\nIf I'm into a pretty large codebase (Angular monorepo) and try to save a file after editing, sometimes the following error occures and I'm unable to save:\r\n\r\n```bash\r\nError detected while processing BufWritePre Autocommands for \"*\":\r\nError executing lua callback: ...vim-macos/share/nvim/runtime/lua/vim/lsp/_watchfiles.lua:85: subcapture nesting too deep\r\n```\r\n\r\n<img width=\"1515\" alt=\"image\" src=\"https://github.com/neovim/neovim/assets/4125222/a46f5c5a-4820-4b8a-a53b-4c62a8f787f7\">\r\n\r\nIf I understand it correctly the autoformatter cannot do its stuff, but I'm not sure. I'm not a neovim ninja, therefore any help is highly appreciated.\r\n\r\n\r\n### Steps to reproduce using \"nvim -u minimal_init.lua\"\r\n\r\n```lua\r\n--- CHANGE THESE\r\nlocal pattern = 'the-filetype'\r\nlocal cmd = {'name-of-language-server-executable'}\r\n-- Add files/folders here that indicate the root of a project\r\nlocal root_markers = {'.git', '.editorconfig'}\r\n-- Change to table with settings if required\r\nlocal settings = vim.empty_dict()\r\n\r\nvim.api.nvim_create_autocmd('FileType', {\r\n  pattern = pattern,\r\n  callback = function(args)\r\n    local match = vim.fs.find(root_markers, { path = args.file, upward = true })[1]\r\n    local root_dir = match and vim.fn.fnamemodify(match, ':p:h') or nil\r\n    vim.lsp.start({\r\n      name = 'bugged-ls',\r\n      cmd = cmd,\r\n      root_dir = root_dir,\r\n      settings = settings\r\n    })\r\n  end\r\n})\r\n```\r\n\r\n### Expected behavior\r\n\r\nthe file should be saved and formatted as usual\r\n\r\n### Neovim version (nvim -v)\r\n\r\nv0.10.0-dev-1801+g2ebd328a7\r\n\r\n### Language server name/version\r\n\r\ntypescript\r\n\r\n### Operating system/version\r\n\r\nMacOS 14.0\r\n\r\n### Log file\r\n\r\n_No response_",
    "closed_at": null,
    "comment_data": [
        {
            "author_association": "MEMBER",
            "body": "relate https://github.com/neovim/neovim/pull/26108",
            "created_at": "2023-12-14T12:38:33Z",
            "html_url": "https://github.com/neovim/neovim/issues/26520#issuecomment-1855777067",
            "id": 1855777067,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/26520",
            "node_id": "IC_kwDOAPphoM5unOkr",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1855777067/reactions"
            },
            "updated_at": "2023-12-14T12:38:33Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1855777067",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/41671631?v=4",
                "events_url": "https://api.github.com/users/glepnir/events{/privacy}",
                "followers_url": "https://api.github.com/users/glepnir/followers",
                "following_url": "https://api.github.com/users/glepnir/following{/other_user}",
                "gists_url": "https://api.github.com/users/glepnir/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/glepnir",
                "id": 41671631,
                "login": "glepnir",
                "node_id": "MDQ6VXNlcjQxNjcxNjMx",
                "organizations_url": "https://api.github.com/users/glepnir/orgs",
                "received_events_url": "https://api.github.com/users/glepnir/received_events",
                "repos_url": "https://api.github.com/users/glepnir/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/glepnir/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/glepnir/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/glepnir"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "This sounds like an issue with the globbing function/lpeg pattern.\r\n\r\nCould you share reproduction steps that one can follow to reproduce the issue?",
            "created_at": "2024-01-02T11:21:09Z",
            "html_url": "https://github.com/neovim/neovim/issues/26520#issuecomment-1873902617",
            "id": 1873902617,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/26520",
            "node_id": "IC_kwDOAPphoM5vsXwZ",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1873902617/reactions"
            },
            "updated_at": "2024-01-02T11:21:09Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1873902617",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/38700?v=4",
                "events_url": "https://api.github.com/users/mfussenegger/events{/privacy}",
                "followers_url": "https://api.github.com/users/mfussenegger/followers",
                "following_url": "https://api.github.com/users/mfussenegger/following{/other_user}",
                "gists_url": "https://api.github.com/users/mfussenegger/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/mfussenegger",
                "id": 38700,
                "login": "mfussenegger",
                "node_id": "MDQ6VXNlcjM4NzAw",
                "organizations_url": "https://api.github.com/users/mfussenegger/orgs",
                "received_events_url": "https://api.github.com/users/mfussenegger/received_events",
                "repos_url": "https://api.github.com/users/mfussenegger/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/mfussenegger/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/mfussenegger/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/mfussenegger"
            }
        },
        {
            "author_association": "NONE",
            "body": "Im seeing this error too - Also running on MacOs on typescript files",
            "created_at": "2024-01-11T11:18:27Z",
            "html_url": "https://github.com/neovim/neovim/issues/26520#issuecomment-1886924732",
            "id": 1886924732,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/26520",
            "node_id": "IC_kwDOAPphoM5weC-8",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1886924732/reactions"
            },
            "updated_at": "2024-01-11T11:18:42Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1886924732",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/3761964?v=4",
                "events_url": "https://api.github.com/users/ChilloManiac/events{/privacy}",
                "followers_url": "https://api.github.com/users/ChilloManiac/followers",
                "following_url": "https://api.github.com/users/ChilloManiac/following{/other_user}",
                "gists_url": "https://api.github.com/users/ChilloManiac/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/ChilloManiac",
                "id": 3761964,
                "login": "ChilloManiac",
                "node_id": "MDQ6VXNlcjM3NjE5NjQ=",
                "organizations_url": "https://api.github.com/users/ChilloManiac/orgs",
                "received_events_url": "https://api.github.com/users/ChilloManiac/received_events",
                "repos_url": "https://api.github.com/users/ChilloManiac/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/ChilloManiac/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/ChilloManiac/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/ChilloManiac"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "Still need reproduction steps.\r\n\r\nA workaround is to turn off the file watching by setting the capabilities in the `vim.lsp.start` config:\r\n\r\n```lua\r\nlocal capabilities = vim.tbl_deep_extend(\r\n  \"force\",\r\n  vim.lsp.protocol.make_client_capabilities(),\r\n  {\r\n    workspace = {\r\n      didChangeWatchedFiles = {\r\n        dynamicRegistration = false\r\n      }\r\n    }\r\n  }\r\n)\r\n```\r\n",
            "created_at": "2024-01-11T14:06:27Z",
            "html_url": "https://github.com/neovim/neovim/issues/26520#issuecomment-1887230243",
            "id": 1887230243,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/26520",
            "node_id": "IC_kwDOAPphoM5wfNkj",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 2,
                "laugh": 0,
                "rocket": 0,
                "total_count": 2,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1887230243/reactions"
            },
            "updated_at": "2024-01-11T14:06:27Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1887230243",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/38700?v=4",
                "events_url": "https://api.github.com/users/mfussenegger/events{/privacy}",
                "followers_url": "https://api.github.com/users/mfussenegger/followers",
                "following_url": "https://api.github.com/users/mfussenegger/following{/other_user}",
                "gists_url": "https://api.github.com/users/mfussenegger/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/mfussenegger",
                "id": 38700,
                "login": "mfussenegger",
                "node_id": "MDQ6VXNlcjM4NzAw",
                "organizations_url": "https://api.github.com/users/mfussenegger/orgs",
                "received_events_url": "https://api.github.com/users/mfussenegger/received_events",
                "repos_url": "https://api.github.com/users/mfussenegger/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/mfussenegger/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/mfussenegger/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/mfussenegger"
            }
        },
        {
            "author_association": "NONE",
            "body": "there is not much to reproducing it. I just try to save a file in the codebase. It occurs when the file is deep in the file tree.\r\nWith the workaround now the error disappeared, so thanks for that!",
            "created_at": "2024-01-26T19:39:02Z",
            "html_url": "https://github.com/neovim/neovim/issues/26520#issuecomment-1912593886",
            "id": 1912593886,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/26520",
            "node_id": "IC_kwDOAPphoM5x_93e",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1912593886/reactions"
            },
            "updated_at": "2024-01-26T19:39:02Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1912593886",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/4125222?v=4",
                "events_url": "https://api.github.com/users/fegyi001/events{/privacy}",
                "followers_url": "https://api.github.com/users/fegyi001/followers",
                "following_url": "https://api.github.com/users/fegyi001/following{/other_user}",
                "gists_url": "https://api.github.com/users/fegyi001/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/fegyi001",
                "id": 4125222,
                "login": "fegyi001",
                "node_id": "MDQ6VXNlcjQxMjUyMjI=",
                "organizations_url": "https://api.github.com/users/fegyi001/orgs",
                "received_events_url": "https://api.github.com/users/fegyi001/received_events",
                "repos_url": "https://api.github.com/users/fegyi001/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/fegyi001/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/fegyi001/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/fegyi001"
            }
        },
        {
            "author_association": "NONE",
            "body": "I am also encountering this error on file open, albeit on a _very_ large (100s of GBs) monorepo with `rust-analyzer`. Tailing `:LspLog` gives\r\n\r\n```\r\n[ERROR][2024-02-09 23:06:30] .../lua/vim/lsp.lua:852    \"LSP[rust_analyzer]\"    \"on_error\"  {  code = \"SERVER_REQUEST_HANDLER_ERROR\",  err = \"/usr/share/nvim/runtime/lua/vim/glob.lua:79: subcapture nesting too deep\"}\r\n```\r\n\r\nwhich points to a \r\n```\r\nlocal lpeg_pattern = Lpeg.P:match(pattern)\r\n```\r\ncall. ",
            "created_at": "2024-02-10T07:13:59Z",
            "html_url": "https://github.com/neovim/neovim/issues/26520#issuecomment-1936910022",
            "id": 1936910022,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/26520",
            "node_id": "IC_kwDOAPphoM5zcubG",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 1,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 1,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1936910022/reactions"
            },
            "updated_at": "2024-02-10T07:13:59Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1936910022",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/13944989?v=4",
                "events_url": "https://api.github.com/users/j1ah0ng/events{/privacy}",
                "followers_url": "https://api.github.com/users/j1ah0ng/followers",
                "following_url": "https://api.github.com/users/j1ah0ng/following{/other_user}",
                "gists_url": "https://api.github.com/users/j1ah0ng/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/j1ah0ng",
                "id": 13944989,
                "login": "j1ah0ng",
                "node_id": "MDQ6VXNlcjEzOTQ0OTg5",
                "organizations_url": "https://api.github.com/users/j1ah0ng/orgs",
                "received_events_url": "https://api.github.com/users/j1ah0ng/received_events",
                "repos_url": "https://api.github.com/users/j1ah0ng/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/j1ah0ng/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/j1ah0ng/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/j1ah0ng"
            }
        },
        {
            "author_association": "NONE",
            "body": "I spent some more time poking around and found [this reference to the error message](https://github.com/edubart/nelua-lang/blob/master/src/lpeglabel/lplcap.c#L457) in `lplcap.c` within the LPeg source: \r\n```c\r\nstatic int pushcapture (CapState *cs) {\r\n  lua_State *L = cs->L;\r\n  int res;\r\n  luaL_checkstack(L, 4, \"too many captures\");\r\n  if (cs->reclevel++ > MAXRECLEVEL)\r\n    return luaL_error(L, \"subcapture nesting too deep\");\r\n\r\n```\r\nthere appears to be a hard-coded `#define MAXRECLEVEL‎ 200` which appears to correspond to the Lua interpreter's max recursion level ([for reference, a -DMAXRECLEVEL compiler flag](https://github.com/edubart/nelua-lang/blob/05a2633a18dfdde7389394b9289da582c10e79bc/Makefile#L32)).\r\n\r\nA cursory search of the neovim repo did not give me a satisfying answer as to what the max depth of the bundled interpreter is: I'm also not sure how LPeg is bundled into neovim, so I'm not certain what the correct way of bumping this number would be.",
            "created_at": "2024-02-10T20:32:16Z",
            "html_url": "https://github.com/neovim/neovim/issues/26520#issuecomment-1937114270",
            "id": 1937114270,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/26520",
            "node_id": "IC_kwDOAPphoM5zdgSe",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1937114270/reactions"
            },
            "updated_at": "2024-02-10T20:32:16Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1937114270",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/13944989?v=4",
                "events_url": "https://api.github.com/users/j1ah0ng/events{/privacy}",
                "followers_url": "https://api.github.com/users/j1ah0ng/followers",
                "following_url": "https://api.github.com/users/j1ah0ng/following{/other_user}",
                "gists_url": "https://api.github.com/users/j1ah0ng/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/j1ah0ng",
                "id": 13944989,
                "login": "j1ah0ng",
                "node_id": "MDQ6VXNlcjEzOTQ0OTg5",
                "organizations_url": "https://api.github.com/users/j1ah0ng/orgs",
                "received_events_url": "https://api.github.com/users/j1ah0ng/received_events",
                "repos_url": "https://api.github.com/users/j1ah0ng/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/j1ah0ng/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/j1ah0ng/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/j1ah0ng"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "Bumping the number isn't going to be an acceptable solution. We need to understand why it is hitting this limit.",
            "created_at": "2024-02-10T20:37:47Z",
            "html_url": "https://github.com/neovim/neovim/issues/26520#issuecomment-1937115249",
            "id": 1937115249,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/26520",
            "node_id": "IC_kwDOAPphoM5zdghx",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1937115249/reactions"
            },
            "updated_at": "2024-02-10T20:37:47Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1937115249",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/7904185?v=4",
                "events_url": "https://api.github.com/users/lewis6991/events{/privacy}",
                "followers_url": "https://api.github.com/users/lewis6991/followers",
                "following_url": "https://api.github.com/users/lewis6991/following{/other_user}",
                "gists_url": "https://api.github.com/users/lewis6991/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/lewis6991",
                "id": 7904185,
                "login": "lewis6991",
                "node_id": "MDQ6VXNlcjc5MDQxODU=",
                "organizations_url": "https://api.github.com/users/lewis6991/orgs",
                "received_events_url": "https://api.github.com/users/lewis6991/received_events",
                "repos_url": "https://api.github.com/users/lewis6991/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/lewis6991/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/lewis6991/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/lewis6991"
            }
        },
        {
            "author_association": "NONE",
            "body": "~I may also be totally off base: found [this](https://neovim.io/doc/user/lua.html#vim.lpeg.setmaxstack()) reference to a `max stack` used by LPeg in particular:~\r\n```\r\nReturns a pattern that matches any single character that appears in the given string (the S stands for Set). As an example, the pattern lpeg.S(\"+-*&zwj;/\") matches any arithmetic operator. Note that, if s is a character (that is, a string of length 1), then lpeg.P(s) is equivalent to lpeg.S(s) which is equivalent to lpeg.R(s..s). Note also that both lpeg.S(\"\") and lpeg.R() are patterns that always fail.\r\n```\r\n\r\nThis did not seem to have an effect: playing with this number to be somewhere between  `16777216` and over whatever the limit is continued to throw the same error. ",
            "created_at": "2024-02-10T20:37:58Z",
            "html_url": "https://github.com/neovim/neovim/issues/26520#issuecomment-1937115283",
            "id": 1937115283,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/26520",
            "node_id": "IC_kwDOAPphoM5zdgiT",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1937115283/reactions"
            },
            "updated_at": "2024-02-10T20:50:56Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1937115283",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/13944989?v=4",
                "events_url": "https://api.github.com/users/j1ah0ng/events{/privacy}",
                "followers_url": "https://api.github.com/users/j1ah0ng/followers",
                "following_url": "https://api.github.com/users/j1ah0ng/following{/other_user}",
                "gists_url": "https://api.github.com/users/j1ah0ng/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/j1ah0ng",
                "id": 13944989,
                "login": "j1ah0ng",
                "node_id": "MDQ6VXNlcjEzOTQ0OTg5",
                "organizations_url": "https://api.github.com/users/j1ah0ng/orgs",
                "received_events_url": "https://api.github.com/users/j1ah0ng/received_events",
                "repos_url": "https://api.github.com/users/j1ah0ng/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/j1ah0ng/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/j1ah0ng/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/j1ah0ng"
            }
        },
        {
            "author_association": "NONE",
            "body": "> Bumping the number isn't going to be an acceptable solution. We need to understand why it is hitting this limit.\r\n\r\nMy suspicion is that the deeply nested directory structure present in my repo is causing some OOB check to fail. Bumping the number is a means to confirm that.\r\n\r\nI also want to point out that my use case is particular nasty given that my working directory is ~5 levels deep within a source tree, and that my `compile_commands` points to codegen source files which live 10s of levels deep within Bazel build cache indirection. ",
            "created_at": "2024-02-10T20:41:26Z",
            "html_url": "https://github.com/neovim/neovim/issues/26520#issuecomment-1937115908",
            "id": 1937115908,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/26520",
            "node_id": "IC_kwDOAPphoM5zdgsE",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 1,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 1,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1937115908/reactions"
            },
            "updated_at": "2024-02-10T20:51:26Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1937115908",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/13944989?v=4",
                "events_url": "https://api.github.com/users/j1ah0ng/events{/privacy}",
                "followers_url": "https://api.github.com/users/j1ah0ng/followers",
                "following_url": "https://api.github.com/users/j1ah0ng/following{/other_user}",
                "gists_url": "https://api.github.com/users/j1ah0ng/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/j1ah0ng",
                "id": 13944989,
                "login": "j1ah0ng",
                "node_id": "MDQ6VXNlcjEzOTQ0OTg5",
                "organizations_url": "https://api.github.com/users/j1ah0ng/orgs",
                "received_events_url": "https://api.github.com/users/j1ah0ng/received_events",
                "repos_url": "https://api.github.com/users/j1ah0ng/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/j1ah0ng/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/j1ah0ng/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/j1ah0ng"
            }
        },
        {
            "author_association": "NONE",
            "body": "Making the change to `MAXRECDEPTH` appears to have gotten rid of the issue: [diff](https://github.com/j1ah0ng/neovim/commit/8f5b977ea406af46375b4a6cc63b8b285506c58e). \r\n\r\nPlacing a `print(debug.traceback())` before the offending line in `glob.lua` seems to substantiate something is going wrong with watching deeply-nested source trees:\r\n```\r\nstack traceback:\r\n^I/usr/share/nvim/runtime/lua/vim/glob.lua:79: in function 'to_lpeg'\r\nPress ENTER or type command to continue\r\n^I/usr/share/nvim/runtime/lua/vim/lsp/_watchfiles.lua:65: in function 'register'\r\nPress ENTER or type command to continue\r\n^I/usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:123: in function </usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:110>\r\nPress ENTER or type command to continue\r\n^I[C]: in function 'pcall'\r\n```",
            "created_at": "2024-02-10T22:18:54Z",
            "html_url": "https://github.com/neovim/neovim/issues/26520#issuecomment-1937273618",
            "id": 1937273618,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/26520",
            "node_id": "IC_kwDOAPphoM5zeHMS",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1937273618/reactions"
            },
            "updated_at": "2024-02-10T22:18:54Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1937273618",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/13944989?v=4",
                "events_url": "https://api.github.com/users/j1ah0ng/events{/privacy}",
                "followers_url": "https://api.github.com/users/j1ah0ng/followers",
                "following_url": "https://api.github.com/users/j1ah0ng/following{/other_user}",
                "gists_url": "https://api.github.com/users/j1ah0ng/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/j1ah0ng",
                "id": 13944989,
                "login": "j1ah0ng",
                "node_id": "MDQ6VXNlcjEzOTQ0OTg5",
                "organizations_url": "https://api.github.com/users/j1ah0ng/orgs",
                "received_events_url": "https://api.github.com/users/j1ah0ng/received_events",
                "repos_url": "https://api.github.com/users/j1ah0ng/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/j1ah0ng/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/j1ah0ng/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/j1ah0ng"
            }
        },
        {
            "author_association": "NONE",
            "body": "Actually instrumenting the pattern also appears to substantiate this:\r\n```\r\n/home/jiahong.long/.cache/bazel/_bazel_jiahong.long/b83d1475e1d59eed9b220ab04e73408d/execroot/cruise_ws/bazel-out/k8-fastbuild/bin/tools/rust/examples/bag_reading/bag_reading_build_script.out_dir/**/*.rs\r\n```\r\n\r\nStrangely, the glob expansion only expands to a single file:\r\n```\r\n❯ echo /home/jiahong.long/.cache/bazel/_bazel_jiahong.long/b83d1475e1d59eed9b220ab04e73408d/execroot/cruise_ws/bazel-out/k8-fastbuild/bin/tools/rust/examples/bag_reading/bag_reading_build_script.out_dir/**/*.rs\r\n/home/jiahong.long/.cache/bazel/_bazel_jiahong.long/b83d1475e1d59eed9b220ab04e73408d/execroot/cruise_ws/bazel-out/k8-fastbuild/bin/tools/rust/examples/bag_reading/bag_reading_build_script.out_dir/msgs.rs\r\n```",
            "created_at": "2024-02-10T22:24:58Z",
            "html_url": "https://github.com/neovim/neovim/issues/26520#issuecomment-1937286206",
            "id": 1937286206,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/26520",
            "node_id": "IC_kwDOAPphoM5zeKQ-",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 1,
                "-1": 0,
                "confused": 0,
                "eyes": 1,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 2,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1937286206/reactions"
            },
            "updated_at": "2024-02-10T22:26:18Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1937286206",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/13944989?v=4",
                "events_url": "https://api.github.com/users/j1ah0ng/events{/privacy}",
                "followers_url": "https://api.github.com/users/j1ah0ng/followers",
                "following_url": "https://api.github.com/users/j1ah0ng/following{/other_user}",
                "gists_url": "https://api.github.com/users/j1ah0ng/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/j1ah0ng",
                "id": 13944989,
                "login": "j1ah0ng",
                "node_id": "MDQ6VXNlcjEzOTQ0OTg5",
                "organizations_url": "https://api.github.com/users/j1ah0ng/orgs",
                "received_events_url": "https://api.github.com/users/j1ah0ng/received_events",
                "repos_url": "https://api.github.com/users/j1ah0ng/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/j1ah0ng/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/j1ah0ng/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/j1ah0ng"
            }
        },
        {
            "author_association": "NONE",
            "body": "I’ve also experienced this issue yesterday for the first time. After creating a new directory with some files in it (using oil.nvim if it helps), that files reproduced this error when I tried to save (had formatter and eslint running on save as well). Probably I was really deep in sub directories but was really strange. The only way to make the formatters work again was to delete that directory and move the files inside to the parent directory.\r\n\r\nhaven’t experienced this before and started some days after updating to version 0.10 but don’t know if it’s derived from this update or if it was because it was really deep into multiple sub directories or even something else ",
            "created_at": "2024-06-04T11:57:39Z",
            "html_url": "https://github.com/neovim/neovim/issues/26520#issuecomment-2147351150",
            "id": 2147351150,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/26520",
            "node_id": "IC_kwDOAPphoM5__fpu",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/2147351150/reactions"
            },
            "updated_at": "2024-06-04T12:13:16Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/2147351150",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/64453275?v=4",
                "events_url": "https://api.github.com/users/BitInByte/events{/privacy}",
                "followers_url": "https://api.github.com/users/BitInByte/followers",
                "following_url": "https://api.github.com/users/BitInByte/following{/other_user}",
                "gists_url": "https://api.github.com/users/BitInByte/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/BitInByte",
                "id": 64453275,
                "login": "BitInByte",
                "node_id": "MDQ6VXNlcjY0NDUzMjc1",
                "organizations_url": "https://api.github.com/users/BitInByte/orgs",
                "received_events_url": "https://api.github.com/users/BitInByte/received_events",
                "repos_url": "https://api.github.com/users/BitInByte/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/BitInByte/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/BitInByte/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/BitInByte"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "Your comment was marked as duplicate because it does not add useful info. That isn't a prompt to add even more comments.",
            "created_at": "2024-06-04T12:37:19Z",
            "html_url": "https://github.com/neovim/neovim/issues/26520#issuecomment-2147430688",
            "id": 2147430688,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/26520",
            "node_id": "IC_kwDOAPphoM5__zEg",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/2147430688/reactions"
            },
            "updated_at": "2024-06-04T12:37:19Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/2147430688",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/1359421?v=4",
                "events_url": "https://api.github.com/users/justinmk/events{/privacy}",
                "followers_url": "https://api.github.com/users/justinmk/followers",
                "following_url": "https://api.github.com/users/justinmk/following{/other_user}",
                "gists_url": "https://api.github.com/users/justinmk/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/justinmk",
                "id": 1359421,
                "login": "justinmk",
                "node_id": "MDQ6VXNlcjEzNTk0MjE=",
                "organizations_url": "https://api.github.com/users/justinmk/orgs",
                "received_events_url": "https://api.github.com/users/justinmk/received_events",
                "repos_url": "https://api.github.com/users/justinmk/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/justinmk/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/justinmk/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/justinmk"
            }
        },
        {
            "author_association": "NONE",
            "body": "What I am trying to understand is, is this ever gonna be considered to be fixed or not? As far as I can see, it still has the label that needs:repro and when a user comments with new insights (don’t know if you read my comment at least but I reference new stuff in there) you just mark as duplicate and even, I can see that this issue has been referenced in some other commits, my question here is, how can that commits reference this issue if, as label indicates, can’t be reproduced? What is the metric here then? Is is reproducible or not in the end since it has been referenced in some other fixes?\r\n\r\ndon’t get me wrong, just want to understand if this will ever be considered or not because I am not the only one reporting and this is kind of a big issue for some people.\r\n\r\nthanks and hope team makes neovim even bigger <3",
            "created_at": "2024-06-04T14:25:04Z",
            "html_url": "https://github.com/neovim/neovim/issues/26520#issuecomment-2147676025",
            "id": 2147676025,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/26520",
            "node_id": "IC_kwDOAPphoM6AAu95",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/2147676025/reactions"
            },
            "updated_at": "2024-06-04T14:58:10Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/2147676025",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/64453275?v=4",
                "events_url": "https://api.github.com/users/BitInByte/events{/privacy}",
                "followers_url": "https://api.github.com/users/BitInByte/followers",
                "following_url": "https://api.github.com/users/BitInByte/following{/other_user}",
                "gists_url": "https://api.github.com/users/BitInByte/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/BitInByte",
                "id": 64453275,
                "login": "BitInByte",
                "node_id": "MDQ6VXNlcjY0NDUzMjc1",
                "organizations_url": "https://api.github.com/users/BitInByte/orgs",
                "received_events_url": "https://api.github.com/users/BitInByte/received_events",
                "repos_url": "https://api.github.com/users/BitInByte/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/BitInByte/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/BitInByte/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/BitInByte"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "> What I am trying to understand is, is this ever gonna be considered to be fixed or not?\r\n\r\nThe issue is still open ... so it is not fixed.\r\n\r\n> As far as I can see, it still has the label that needs:repro and when a user comments with new insights (don’t know if you read my comment at least but I reference new stuff in there) you just mark as duplicate and even, I can see that this issue has been referenced in some other commits, my question here is, how can that commits reference this issue if, as label indicates, can’t be reproduced? What is the metric here then? Is is reproducible or not in the end since it has been referenced in some other fixes?\r\n\r\nReproduction steps have yet to be provided. Your comment did not provide any, nor any useful information.\r\n\r\nIf a dev can't reproduce the issue, they cannot fix it. I don't know what is difficult to understand about that.\r\n\r\nFor anyone reading please refrain from any comments like:\r\n- \"I'm seeing this issue too\"\r\n- \"This didn't happen on version 0.x\"\r\n- \"When running this plugin (with this plugin)^n, the issue occurs\".\r\n\r\nPlease **DO** comment if you can provide precise steps in the form of commands with a minimal init.lua that produces the issue., **just as the issue template instructs**.",
            "created_at": "2024-06-04T14:58:00Z",
            "html_url": "https://github.com/neovim/neovim/issues/26520#issuecomment-2147754642",
            "id": 2147754642,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/26520",
            "node_id": "IC_kwDOAPphoM6ABCKS",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/2147754642/reactions"
            },
            "updated_at": "2024-06-04T14:58:35Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/2147754642",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/7904185?v=4",
                "events_url": "https://api.github.com/users/lewis6991/events{/privacy}",
                "followers_url": "https://api.github.com/users/lewis6991/followers",
                "following_url": "https://api.github.com/users/lewis6991/following{/other_user}",
                "gists_url": "https://api.github.com/users/lewis6991/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/lewis6991",
                "id": 7904185,
                "login": "lewis6991",
                "node_id": "MDQ6VXNlcjc5MDQxODU=",
                "organizations_url": "https://api.github.com/users/lewis6991/orgs",
                "received_events_url": "https://api.github.com/users/lewis6991/received_events",
                "repos_url": "https://api.github.com/users/lewis6991/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/lewis6991/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/lewis6991/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/lewis6991"
            }
        }
    ],
    "comments": 16,
    "comments_url": "https://api.github.com/repos/neovim/neovim/issues/26520/comments",
    "created_at": "2023-12-11T20:04:18Z",
    "events_url": "https://api.github.com/repos/neovim/neovim/issues/26520/events",
    "html_url": "https://github.com/neovim/neovim/issues/26520",
    "id": 2036435053,
    "labels": [
        {
            "color": "f9d0c4",
            "default": true,
            "description": "issues reporting wrong behavior",
            "id": 77997474,
            "name": "bug",
            "node_id": "MDU6TGFiZWw3Nzk5NzQ3NA==",
            "url": "https://api.github.com/repos/neovim/neovim/labels/bug"
        },
        {
            "color": "FBCA04",
            "default": false,
            "description": "We need minimal steps to reproduce the issue",
            "id": 298863445,
            "name": "needs:repro",
            "node_id": "MDU6TGFiZWwyOTg4NjM0NDU=",
            "url": "https://api.github.com/repos/neovim/neovim/labels/needs:repro"
        },
        {
            "color": "c5def5",
            "default": false,
            "description": null,
            "id": 662566370,
            "name": "lsp",
            "node_id": "MDU6TGFiZWw2NjI1NjYzNzA=",
            "url": "https://api.github.com/repos/neovim/neovim/labels/lsp"
        }
    ],
    "labels_url": "https://api.github.com/repos/neovim/neovim/issues/26520/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "I_kwDOAPphoM55YYht",
    "number": 26520,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 1,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 1,
        "url": "https://api.github.com/repos/neovim/neovim/issues/26520/reactions"
    },
    "repository_url": "https://api.github.com/repos/neovim/neovim",
    "state": "open",
    "state_reason": null,
    "timeline_url": "https://api.github.com/repos/neovim/neovim/issues/26520/timeline",
    "title": "LSP: big workspace causes \"subcapture nesting too deep\" error in Lpeg.P:match",
    "updated_at": "2024-06-04T14:58:35Z",
    "url": "https://api.github.com/repos/neovim/neovim/issues/26520",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/4125222?v=4",
        "events_url": "https://api.github.com/users/fegyi001/events{/privacy}",
        "followers_url": "https://api.github.com/users/fegyi001/followers",
        "following_url": "https://api.github.com/users/fegyi001/following{/other_user}",
        "gists_url": "https://api.github.com/users/fegyi001/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/fegyi001",
        "id": 4125222,
        "login": "fegyi001",
        "node_id": "MDQ6VXNlcjQxMjUyMjI=",
        "organizations_url": "https://api.github.com/users/fegyi001/orgs",
        "received_events_url": "https://api.github.com/users/fegyi001/received_events",
        "repos_url": "https://api.github.com/users/fegyi001/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/fegyi001/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/fegyi001/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/fegyi001"
    }
}