{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "NONE",
    "body": "### Problem\n\nHi all, \r\n`vim.diagnostic.show` results in an error when underline is set to false. \r\nThe lua code below works fine when `underline = true` or commented out.\r\nThe error occurs when `underline = false` AND we switch from `vim.diagnostic.hide()` to `vim.diagnostic.show()`. I've included a keymap to toggle the diagnostic settings.\r\n\r\nI find this weird behavior given there is no obvious relation between vim.diagnostic.show() and underline.\r\n```Lua\r\n    'neovim/nvim-lspconfig',\r\n    lazy = false,\r\n    config = function()\r\n      -- default diagnostic settings\r\n      vim.diagnostic.config({\r\n        update_in_insert = false,\r\n        virtual_text = false,\r\n        signs = true,\r\n        underline = false,\r\n        severity_sort = true,\r\n        float = {\r\n          source = \"always\", -- Or \"if_many\"\r\n          border = 'rounded'\r\n        },\r\n      })\r\n\r\n      vim.g.diagnostics_state = 1\r\n      \r\n      local function refresh_diagnostics_screen()\r\n        -- to refresh lsp diagnostics on screen trigger an InsertLeave event\r\n        -- else use: vim.cmd([[ LspRestart ]]) which is slower\r\n        vim.api.nvim_buf_set_lines(0, 0, 0, false, { \" \" })\r\n        vim.api.nvim_buf_set_lines(0, 0, 1, false, {})\r\n        vim.diagnostic.show()\r\n      end\r\n\r\n      local function toggle_diagnostics()\r\n        -- toggle diagnostics between:\r\n        -- 0 no diagnostics\r\n        -- 1 only in signcolumn\r\n        -- 2 virtualtext and signcolumn\r\n\r\n        vim.g.diagnostics_state = (vim.g.diagnostics_state + 1) % 3\r\n\r\n        if vim.g.diagnostics_state == 0 then\r\n          vim.diagnostic.hide()\r\n          print(\"Diagnostics: Hidden\")\r\n        elseif vim.g.diagnostics_state == 1 then\r\n          vim.lsp.handlers[\"textDocument/publishDiagnostics\"] = vim.lsp.with(\r\n            vim.lsp.diagnostic.on_publish_diagnostics, {\r\n              virtual_text = false,\r\n            }\r\n          )\r\n          refresh_diagnostics_screen()\r\n          print(\"Diagnostics: Signs only\")\r\n        elseif vim.g.diagnostics_state == 2 then\r\n          vim.lsp.handlers[\"textDocument/publishDiagnostics\"] = vim.lsp.with(\r\n            vim.lsp.diagnostic.on_publish_diagnostics, {\r\n              virtual_text = {\r\n                -- source = \"always\",  -- Or \"if_many\"\r\n                prefix = '●', -- Could be '■', '▎', 'x'\r\n              },\r\n            }\r\n          )\r\n          refresh_diagnostics_screen()\r\n          print(\"Diagnostics: Virtual text and Signs\")\r\n        end\r\n      end\r\n      vim.keymap.set('n', '<leader>dt', toggle_diagnostics, { desc = 'Diagnostics [T]oggle' })\r\n\r\n```\r\nBasically I'm changing the virtual text and sign settings in vim.diagnostic.config and then update the diagnostics displayed on screen. After some toggle-cycles I get an error when we switch from vim.diagnostic.hide() to vim.diagnostic.show(). :\r\n```\r\nE5108: Error executing lua: ...ashfs-root/usr/share/nvim/runtime/lua/vim/diagnostic.lua:1031: Invalid 'line': out of range\r\nstack traceback:\r\n        [C]: in function 'nvim_buf_set_extmark'\r\n        ...ashfs-root/usr/share/nvim/runtime/lua/vim/diagnostic.lua:1031: in function 'show'\r\n```\r\nI'm not able to resolve this issue, and it only occurs if `underline = false` \r\nIs this a bug or should this be done differently?\r\n\n\n### Steps to reproduce\n\nCopy the config into the nvim-lspconfig config table\n\n### Expected behavior\n\nThe setting of `underline = false` should not trigger this error, and should behave similar to setting `underline = true` (which works fine).\r\n\n\n### Neovim version (nvim -v)\n\nNVIM v0.9.1\n\n### Vim (not Nvim) behaves the same?\n\nno\n\n### Operating system/version\n\nDebian 12\n\n### Terminal name/version\n\nGNOME Terminal Version 3.46.8 for GNOME 43\n\n### $TERM environment variable\n\nxterm-256color\n\n### Installation\n\nappimage",
    "closed_at": "2024-01-07T18:09:10Z",
    "comment_data": [
        {
            "author_association": "NONE",
            "body": "I've deleted my Nvim cache, state and data folders and reinstalled the lsp servers. \r\nNow all seems fine.",
            "created_at": "2024-01-07T18:09:10Z",
            "html_url": "https://github.com/neovim/neovim/issues/26940#issuecomment-1880129820",
            "id": 1880129820,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/26940",
            "node_id": "IC_kwDOAPphoM5wEIEc",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1880129820/reactions"
            },
            "updated_at": "2024-01-07T18:09:10Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1880129820",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/123158194?v=4",
                "events_url": "https://api.github.com/users/aedificatio/events{/privacy}",
                "followers_url": "https://api.github.com/users/aedificatio/followers",
                "following_url": "https://api.github.com/users/aedificatio/following{/other_user}",
                "gists_url": "https://api.github.com/users/aedificatio/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/aedificatio",
                "id": 123158194,
                "login": "aedificatio",
                "node_id": "U_kgDOB1c-sg",
                "organizations_url": "https://api.github.com/users/aedificatio/orgs",
                "received_events_url": "https://api.github.com/users/aedificatio/received_events",
                "repos_url": "https://api.github.com/users/aedificatio/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/aedificatio/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/aedificatio/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/aedificatio"
            }
        }
    ],
    "comments": 1,
    "comments_url": "https://api.github.com/repos/neovim/neovim/issues/26940/comments",
    "created_at": "2024-01-07T10:55:54Z",
    "events_url": "https://api.github.com/repos/neovim/neovim/issues/26940/events",
    "html_url": "https://github.com/neovim/neovim/issues/26940",
    "id": 2069083044,
    "labels": [
        {
            "color": "f9d0c4",
            "default": true,
            "description": "issues reporting wrong behavior",
            "id": 77997474,
            "name": "bug",
            "node_id": "MDU6TGFiZWw3Nzk5NzQ3NA==",
            "url": "https://api.github.com/repos/neovim/neovim/labels/bug"
        },
        {
            "color": "C5DEF5",
            "default": false,
            "description": "",
            "id": 3361645105,
            "name": "diagnostic",
            "node_id": "MDU6TGFiZWwzMzYxNjQ1MTA1",
            "url": "https://api.github.com/repos/neovim/neovim/labels/diagnostic"
        }
    ],
    "labels_url": "https://api.github.com/repos/neovim/neovim/issues/26940/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "I_kwDOAPphoM57U7Ok",
    "number": 26940,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 0,
        "url": "https://api.github.com/repos/neovim/neovim/issues/26940/reactions"
    },
    "repository_url": "https://api.github.com/repos/neovim/neovim",
    "state": "closed",
    "state_reason": "completed",
    "timeline_url": "https://api.github.com/repos/neovim/neovim/issues/26940/timeline",
    "title": "vim.diagnostic.show results in an Error when underline = false",
    "updated_at": "2024-01-07T18:09:10Z",
    "url": "https://api.github.com/repos/neovim/neovim/issues/26940",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/123158194?v=4",
        "events_url": "https://api.github.com/users/aedificatio/events{/privacy}",
        "followers_url": "https://api.github.com/users/aedificatio/followers",
        "following_url": "https://api.github.com/users/aedificatio/following{/other_user}",
        "gists_url": "https://api.github.com/users/aedificatio/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/aedificatio",
        "id": 123158194,
        "login": "aedificatio",
        "node_id": "U_kgDOB1c-sg",
        "organizations_url": "https://api.github.com/users/aedificatio/orgs",
        "received_events_url": "https://api.github.com/users/aedificatio/received_events",
        "repos_url": "https://api.github.com/users/aedificatio/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/aedificatio/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/aedificatio/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/aedificatio"
    }
}