{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "NONE",
    "body": "### Problem\r\n\r\nI tried to start lsp client and set buffer option to v:lua.vim.lsp.omnifunc during LspAttach event. \r\nI have no other configuration (keymaps, options, plugins.. etc) in init.lua other than below:\r\n\r\nHowever, I noticed the omnifunc is getting overriden somewhere when starting up the nvim. After the buffer got its window, I source my init.lua (:source $MYVIMRC)  and the lsp works fine. \r\nBefore sourcing $MYVIMRC:\r\n<img width=\"681\" alt=\"image\" src=\"https://github.com/neovim/neovim/assets/47608189/d1d82e35-0c92-48b6-9ae6-51fb2f155385\">\r\n\r\nAfter sourcing $MYVIMRC\r\n<img width=\"704\" alt=\"image\" src=\"https://github.com/neovim/neovim/assets/47608189/a5679bb5-8549-4bbf-962b-318942d3a5bb\">\r\n\r\n### Steps to reproduce\r\n\r\n1. nvim init.lua\r\n\r\n2. copy the following code into file:\r\n```\r\n-- Configure Language Servers\r\nvim.lsp.start({\r\n  name = \"pyright\",\r\n  cmd = { \"pyright-langserver\", \"--stdio\" },\r\n  root_dir = vim.fs.dirname(vim.fs.find({\r\n    'pyproject.toml', 'setup.py', 'requirements.txt'}, { upward = true })[1]),\r\n})\r\n\r\nvim.api.nvim_create_autocmd('LspAttach', {\r\n  group = vim.api.nvim_create_augroup('UserLspConfig', {}),\r\n  callback = function(args)\r\n    -- Enable completion triggered by <c-x><c-o>\r\n    local bufnr = args.buf\r\n    local client = vim.lsp.get_client_by_id(args.data.client_id)\r\n    print(\"client id\")\r\n    if client.server_capabilities.completionProvider then\r\n      vim.bo[bufnr].omnifunc = \"v:lua.vim.lsp.omnifunc\"\r\n      print(\"in if function\")\r\n      print(tostring(vim.bo[bufnr].omnifunc))\r\n    end\r\n    print(\"out of if function\")\r\n    if client.server_capabilities.definitionProvider then\r\n      vim.bo[bufnr].tagfunc = \"v:lua.vim.lsp.tagfunc\"\r\n    end\r\n    -- Buffer local mappings.\r\n    -- See `:help vim.lsp.*` for documentation on any of the below functions\r\n    local opts = { buffer = args.buf }\r\n    vim.keymap.set('n', 'gD', vim.lsp.buf.declaration, opts)\r\n    vim.keymap.set('n', 'gd', vim.lsp.buf.definition, opts)\r\n    vim.keymap.set('n', 'K', vim.lsp.buf.hover, opts)\r\n    vim.keymap.set('n', 'gi', vim.lsp.buf.implementation, opts)\r\n    vim.keymap.set('n', '<C-k>', vim.lsp.buf.signature_help, opts)\r\n    vim.keymap.set('n', '<space>wa', vim.lsp.buf.add_workspace_folder, opts)\r\n    vim.keymap.set('n', '<space>wr', vim.lsp.buf.remove_workspace_folder, opts)\r\n    vim.keymap.set('n', '<space>wl', function()\r\n      print(vim.inspect(vim.lsp.buf.list_workspace_folders()))\r\n    end, opts)\r\n    vim.keymap.set('n', '<space>D', vim.lsp.buf.type_definition, opts)\r\n    vim.keymap.set('n', '<space>rn', vim.lsp.buf.rename, opts)\r\n    vim.keymap.set({ 'n', 'v' }, '<space>ca', vim.lsp.buf.code_action, opts)\r\n    vim.keymap.set('n', 'gr', vim.lsp.buf.references, opts)\r\n    vim.keymap.set('n', '<space>f', function()\r\n      vim.lsp.buf.format { async = true }\r\n    end, opts)\r\n  end,\r\n})\r\n```\r\n\r\n3. Then save, quit and reopen to see lsp did not attach. You would get no errors pointed out. Running following command```:verbose set omnifunc``` returns ``Ã²mnifunc=```\r\n5. After sourcing with :source $MYVIMRC, lsp gets attached and configured features work. As I have placed few prints in the autocommand for debugging, the following gets printed from which i infer that autocommands ran\r\n<img width=\"465\" alt=\"image\" src=\"https://github.com/neovim/neovim/assets/47608189/e730cbf4-c22a-46de-bc08-3c75c3b50a15\">\r\n\r\nSince, the configuration is for language-server pyright. Here is diagnosis for python file:\r\nFolder structure:\r\n<img width=\"302\" alt=\"image\" src=\"https://github.com/neovim/neovim/assets/47608189/dd95daa9-e6f7-44b8-b4cc-7ef91703417e\">\r\npyright language server is installed as well\r\n<img width=\"589\" alt=\"image\" src=\"https://github.com/neovim/neovim/assets/47608189/7d7c65e3-2a4c-47dc-a029-054c1d4a0cce\">\r\n\r\n1. Open file: nvim encode_decode_strings.py \r\n2. Before sourcing, shows no error and omnifunc is not set\r\n<img width=\"532\" alt=\"image\" src=\"https://github.com/neovim/neovim/assets/47608189/2542c2e5-e8d3-4c7d-8a0c-c1f39603833a\">\r\n\r\n3. Upon running ```:source $MYVIMRC```, the LspAttach autocommand does run (as seen from print below status line) but no errors are shown (not sure why it works with lua file). And running ```:verbose set omnifunc?``` returns ```v:lua.vim.lsp.omnifunc```\r\n<img width=\"594\" alt=\"image\" src=\"https://github.com/neovim/neovim/assets/47608189/15a2c6a5-7371-4908-9491-a520d0788af4\">\r\n\r\n\r\n### Expected behavior\r\n\r\nFollowing the documentation and with no extra plugins installed, I expected the lsp completion would work out of the box. I did not expect it to get overriden. Also I am not sure why errors are shown for Lua file but not for Python file\r\n\r\n### Neovim version (nvim -v)\r\n\r\n0.9.5 release\r\n\r\n### Vim (not Nvim) behaves the same?\r\n\r\nno, lsp feature\r\n\r\n### Operating system/version\r\n\r\nMacOs Sonoma 14.4.1\r\n\r\n### Terminal name/version\r\n\r\niTerm2 3.4.3\r\n\r\n### $TERM environment variable\r\n\r\nxterm-256color\r\n\r\n### Installation\r\n\r\nhomebrew",
    "closed_at": "2024-04-13T16:53:37Z",
    "comment_data": [
        {
            "author_association": "MEMBER",
            "body": "What does `:verbose set omnifunc?` print after it gets overridden?",
            "created_at": "2024-04-13T09:14:56Z",
            "html_url": "https://github.com/neovim/neovim/issues/28313#issuecomment-2053585317",
            "id": 2053585317,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/28313",
            "node_id": "IC_kwDOAPphoM56Zzml",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/2053585317/reactions"
            },
            "updated_at": "2024-04-13T09:14:56Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/2053585317",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/35768171?v=4",
                "events_url": "https://api.github.com/users/zeertzjq/events{/privacy}",
                "followers_url": "https://api.github.com/users/zeertzjq/followers",
                "following_url": "https://api.github.com/users/zeertzjq/following{/other_user}",
                "gists_url": "https://api.github.com/users/zeertzjq/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/zeertzjq",
                "id": 35768171,
                "login": "zeertzjq",
                "node_id": "MDQ6VXNlcjM1NzY4MTcx",
                "organizations_url": "https://api.github.com/users/zeertzjq/orgs",
                "received_events_url": "https://api.github.com/users/zeertzjq/received_events",
                "repos_url": "https://api.github.com/users/zeertzjq/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/zeertzjq/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/zeertzjq/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/zeertzjq"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "The steps to reproduce don't look right. The only language server you have configured is pyright, but in the screenshot the diagnostics are for Lua.",
            "created_at": "2024-04-13T09:17:14Z",
            "html_url": "https://github.com/neovim/neovim/issues/28313#issuecomment-2053585901",
            "id": 2053585901,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/28313",
            "node_id": "IC_kwDOAPphoM56Zzvt",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/2053585901/reactions"
            },
            "updated_at": "2024-04-13T09:17:49Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/2053585901",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/35768171?v=4",
                "events_url": "https://api.github.com/users/zeertzjq/events{/privacy}",
                "followers_url": "https://api.github.com/users/zeertzjq/followers",
                "following_url": "https://api.github.com/users/zeertzjq/following{/other_user}",
                "gists_url": "https://api.github.com/users/zeertzjq/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/zeertzjq",
                "id": 35768171,
                "login": "zeertzjq",
                "node_id": "MDQ6VXNlcjM1NzY4MTcx",
                "organizations_url": "https://api.github.com/users/zeertzjq/orgs",
                "received_events_url": "https://api.github.com/users/zeertzjq/received_events",
                "repos_url": "https://api.github.com/users/zeertzjq/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/zeertzjq/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/zeertzjq/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/zeertzjq"
            }
        },
        {
            "author_association": "NONE",
            "body": "I have edited the issue with diagnostics for python file next to setup.py and requirements.txt both, though I know only one of them source attach the lsp client based on configuration in init.lua file. However, it is weird, the lsp error detection does not work at all for python file but works for lua file. ",
            "created_at": "2024-04-13T12:31:40Z",
            "html_url": "https://github.com/neovim/neovim/issues/28313#issuecomment-2053633676",
            "id": 2053633676,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/28313",
            "node_id": "IC_kwDOAPphoM56Z_aM",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/2053633676/reactions"
            },
            "updated_at": "2024-04-13T12:31:40Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/2053633676",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/47608189?v=4",
                "events_url": "https://api.github.com/users/barunps3/events{/privacy}",
                "followers_url": "https://api.github.com/users/barunps3/followers",
                "following_url": "https://api.github.com/users/barunps3/following{/other_user}",
                "gists_url": "https://api.github.com/users/barunps3/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/barunps3",
                "id": 47608189,
                "login": "barunps3",
                "node_id": "MDQ6VXNlcjQ3NjA4MTg5",
                "organizations_url": "https://api.github.com/users/barunps3/orgs",
                "received_events_url": "https://api.github.com/users/barunps3/received_events",
                "repos_url": "https://api.github.com/users/barunps3/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/barunps3/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/barunps3/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/barunps3"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "I think you are not following the documentation. The documentation mentions:\r\n```\r\n    To ensure a language server is only started for languages it can handle,\r\n    make sure to call |vim.lsp.start()| within a |FileType| autocmd. Either\r\n    use |:au|, |nvim_create_autocmd()| or put the call in a\r\n    `ftplugin/<filetype_name>.lua` (See |ftplugin-name|)\r\n```\r\nBut you are calling `vim.lsp.start()` directly in `init.lua`.",
            "created_at": "2024-04-13T12:38:41Z",
            "html_url": "https://github.com/neovim/neovim/issues/28313#issuecomment-2053635242",
            "id": 2053635242,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/28313",
            "node_id": "IC_kwDOAPphoM56Z_yq",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/2053635242/reactions"
            },
            "updated_at": "2024-04-13T12:38:41Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/2053635242",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/35768171?v=4",
                "events_url": "https://api.github.com/users/zeertzjq/events{/privacy}",
                "followers_url": "https://api.github.com/users/zeertzjq/followers",
                "following_url": "https://api.github.com/users/zeertzjq/following{/other_user}",
                "gists_url": "https://api.github.com/users/zeertzjq/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/zeertzjq",
                "id": 35768171,
                "login": "zeertzjq",
                "node_id": "MDQ6VXNlcjM1NzY4MTcx",
                "organizations_url": "https://api.github.com/users/zeertzjq/orgs",
                "received_events_url": "https://api.github.com/users/zeertzjq/received_events",
                "repos_url": "https://api.github.com/users/zeertzjq/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/zeertzjq/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/zeertzjq/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/zeertzjq"
            }
        },
        {
            "author_association": "NONE",
            "body": "Thank you for guiding me to right place. I did make the changes and yes when I open a python file the omnifunc is set correctly. \r\nCurrent change in init.lua file\r\n<img width=\"659\" alt=\"image\" src=\"https://github.com/neovim/neovim/assets/47608189/292b3046-7cf1-4167-8150-1a61a9b9fd19\">\r\n\r\nHowever, the python file highlights no errors like it did for init.lua and when I press Ctrl+x Ctrl+o it does not open completion drop down\r\n<img width=\"505\" alt=\"image\" src=\"https://github.com/neovim/neovim/assets/47608189/d202ebf9-6485-49cc-9ecc-a05d3f9ef262\">\r\n\r\nCan you please tell, why it does not work ? I am new to neovim and lost in documentation. \r\n",
            "created_at": "2024-04-13T14:09:07Z",
            "html_url": "https://github.com/neovim/neovim/issues/28313#issuecomment-2053657020",
            "id": 2053657020,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/28313",
            "node_id": "IC_kwDOAPphoM56aFG8",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/2053657020/reactions"
            },
            "updated_at": "2024-04-13T14:09:07Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/2053657020",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/47608189?v=4",
                "events_url": "https://api.github.com/users/barunps3/events{/privacy}",
                "followers_url": "https://api.github.com/users/barunps3/followers",
                "following_url": "https://api.github.com/users/barunps3/following{/other_user}",
                "gists_url": "https://api.github.com/users/barunps3/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/barunps3",
                "id": 47608189,
                "login": "barunps3",
                "node_id": "MDQ6VXNlcjQ3NjA4MTg5",
                "organizations_url": "https://api.github.com/users/barunps3/orgs",
                "received_events_url": "https://api.github.com/users/barunps3/received_events",
                "repos_url": "https://api.github.com/users/barunps3/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/barunps3/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/barunps3/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/barunps3"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "I don't know. I tested it and it works.",
            "created_at": "2024-04-13T14:26:45Z",
            "html_url": "https://github.com/neovim/neovim/issues/28313#issuecomment-2053661803",
            "id": 2053661803,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/28313",
            "node_id": "IC_kwDOAPphoM56aGRr",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/2053661803/reactions"
            },
            "updated_at": "2024-04-13T14:26:45Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/2053661803",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/35768171?v=4",
                "events_url": "https://api.github.com/users/zeertzjq/events{/privacy}",
                "followers_url": "https://api.github.com/users/zeertzjq/followers",
                "following_url": "https://api.github.com/users/zeertzjq/following{/other_user}",
                "gists_url": "https://api.github.com/users/zeertzjq/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/zeertzjq",
                "id": 35768171,
                "login": "zeertzjq",
                "node_id": "MDQ6VXNlcjM1NzY4MTcx",
                "organizations_url": "https://api.github.com/users/zeertzjq/orgs",
                "received_events_url": "https://api.github.com/users/zeertzjq/received_events",
                "repos_url": "https://api.github.com/users/zeertzjq/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/zeertzjq/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/zeertzjq/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/zeertzjq"
            }
        },
        {
            "author_association": "NONE",
            "body": "It works for me now. All I did was create python file in .config/nvim directory. I am not sure what could have changed. However, I am closing this issue. ",
            "created_at": "2024-04-13T16:53:37Z",
            "html_url": "https://github.com/neovim/neovim/issues/28313#issuecomment-2053700339",
            "id": 2053700339,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/28313",
            "node_id": "IC_kwDOAPphoM56aPrz",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/2053700339/reactions"
            },
            "updated_at": "2024-04-13T16:53:37Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/2053700339",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/47608189?v=4",
                "events_url": "https://api.github.com/users/barunps3/events{/privacy}",
                "followers_url": "https://api.github.com/users/barunps3/followers",
                "following_url": "https://api.github.com/users/barunps3/following{/other_user}",
                "gists_url": "https://api.github.com/users/barunps3/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/barunps3",
                "id": 47608189,
                "login": "barunps3",
                "node_id": "MDQ6VXNlcjQ3NjA4MTg5",
                "organizations_url": "https://api.github.com/users/barunps3/orgs",
                "received_events_url": "https://api.github.com/users/barunps3/received_events",
                "repos_url": "https://api.github.com/users/barunps3/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/barunps3/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/barunps3/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/barunps3"
            }
        }
    ],
    "comments": 7,
    "comments_url": "https://api.github.com/repos/neovim/neovim/issues/28313/comments",
    "created_at": "2024-04-13T09:03:00Z",
    "events_url": "https://api.github.com/repos/neovim/neovim/issues/28313/events",
    "html_url": "https://github.com/neovim/neovim/issues/28313",
    "id": 2241443936,
    "labels": [
        {
            "color": "f9d0c4",
            "default": true,
            "description": "issues reporting wrong behavior",
            "id": 77997474,
            "name": "bug",
            "node_id": "MDU6TGFiZWw3Nzk5NzQ3NA==",
            "url": "https://api.github.com/repos/neovim/neovim/labels/bug"
        },
        {
            "color": "FBCA04",
            "default": false,
            "description": "We need minimal steps to reproduce the issue",
            "id": 298863445,
            "name": "needs:repro",
            "node_id": "MDU6TGFiZWwyOTg4NjM0NDU=",
            "url": "https://api.github.com/repos/neovim/neovim/labels/needs:repro"
        }
    ],
    "labels_url": "https://api.github.com/repos/neovim/neovim/issues/28313/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "I_kwDOAPphoM6Fmbhg",
    "number": 28313,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 0,
        "url": "https://api.github.com/repos/neovim/neovim/issues/28313/reactions"
    },
    "repository_url": "https://api.github.com/repos/neovim/neovim",
    "state": "closed",
    "state_reason": "completed",
    "timeline_url": "https://api.github.com/repos/neovim/neovim/issues/28313/timeline",
    "title": "omnifunc value gets overriden even when no additional plugins installed",
    "updated_at": "2024-04-13T16:53:37Z",
    "url": "https://api.github.com/repos/neovim/neovim/issues/28313",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/47608189?v=4",
        "events_url": "https://api.github.com/users/barunps3/events{/privacy}",
        "followers_url": "https://api.github.com/users/barunps3/followers",
        "following_url": "https://api.github.com/users/barunps3/following{/other_user}",
        "gists_url": "https://api.github.com/users/barunps3/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/barunps3",
        "id": 47608189,
        "login": "barunps3",
        "node_id": "MDQ6VXNlcjQ3NjA4MTg5",
        "organizations_url": "https://api.github.com/users/barunps3/orgs",
        "received_events_url": "https://api.github.com/users/barunps3/received_events",
        "repos_url": "https://api.github.com/users/barunps3/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/barunps3/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/barunps3/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/barunps3"
    }
}