{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "NONE",
    "body": "### Problem\n\nAfter updating neovim to 0.10.1 via my package manager, filetypes are not detected correctly anymore.\r\n\r\nInstead, when I start neovim, it will show the following error message in the minibuffer:\r\n\r\n```\r\nError detected while processing BufReadPost Autocommands for \"*\":\r\nError executing lua callback: .../share/nvim/lazy/LazyVim/lua/lazyvim/config/autocmds.lua:130:\r\nattempt to compare nil with number\r\nstack traceback:\r\n        .../share/nvim/lazy/LazyVim/lua/lazyvim/config/autocmds.lua:130: in function 'ft'\r\n        vim/filetype.lua:2368: in function 'dispatch'\r\n        vim/filetype.lua:2535: in function 'match'\r\n        /usr/share/nvim/runtime/filetype.lua:14: in function </usr/share/nvim/runtime/filetype.\r\nlua:10>\r\n```\r\n\r\nIf I press `Enter`, the file will be opened but without any highlighting, plus the filetype in the info bar always says `unix`.\r\n\r\nI checked the mentioned files at the named lines, but my knowledge of those nvim internal things is non-existing.\r\n\r\nI did not make any changes to my neovim config since the update.\n\n### Steps to reproduce\n\nUnclear. Tried with the `minimal.lua` conf file, but nearly had to include my whole `init.lua` to reproduce the error.\n\n### Expected behavior\n\nFiletypes should be detected automatically as regular.\n\n### Neovim version (nvim -v)\n\nNVIM v0.10.1 Build type: None LuaJIT 2.1.1720049189\n\n### Vim (not Nvim) behaves the same?\n\nno\n\n### Operating system/version\n\nVoid Linux\n\n### Terminal name/version\n\nfoot version: 1.17.2 -pgo +ime +graphemes -assertions\n\n### $TERM environment variable\n\nfoot\n\n### Installation\n\nxbps-install -Su neovim",
    "closed_at": "2024-07-31T15:21:40Z",
    "closed_by": {
        "avatar_url": "https://avatars.githubusercontent.com/u/2361214?v=4",
        "events_url": "https://api.github.com/users/clason/events{/privacy}",
        "followers_url": "https://api.github.com/users/clason/followers",
        "following_url": "https://api.github.com/users/clason/following{/other_user}",
        "gists_url": "https://api.github.com/users/clason/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/clason",
        "id": 2361214,
        "login": "clason",
        "node_id": "MDQ6VXNlcjIzNjEyMTQ=",
        "organizations_url": "https://api.github.com/users/clason/orgs",
        "received_events_url": "https://api.github.com/users/clason/received_events",
        "repos_url": "https://api.github.com/users/clason/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/clason/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/clason/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/clason"
    },
    "comment_data": [
        {
            "author_association": "MEMBER",
            "body": "Obviously this is an issue with your config, since filetype detection is tested in our CI. The usual approach is required here: start with `nvim --clean`, and then add `nvim --clean -u test.lua`, adding settings and plugins from your config to `test.lua` _one by one_. The culprit is virtually guaranteed to be a plugin.",
            "created_at": "2024-07-29T08:31:16Z",
            "html_url": "https://github.com/neovim/neovim/issues/29900#issuecomment-2255324520",
            "id": 2255324520,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/29900",
            "node_id": "IC_kwDOAPphoM6GbYVo",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/2255324520/reactions"
            },
            "updated_at": "2024-07-29T08:31:16Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/2255324520",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/2361214?v=4",
                "events_url": "https://api.github.com/users/clason/events{/privacy}",
                "followers_url": "https://api.github.com/users/clason/followers",
                "following_url": "https://api.github.com/users/clason/following{/other_user}",
                "gists_url": "https://api.github.com/users/clason/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/clason",
                "id": 2361214,
                "login": "clason",
                "node_id": "MDQ6VXNlcjIzNjEyMTQ=",
                "organizations_url": "https://api.github.com/users/clason/orgs",
                "received_events_url": "https://api.github.com/users/clason/received_events",
                "repos_url": "https://api.github.com/users/clason/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/clason/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/clason/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/clason"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "And we do not support LazyVim; if you cannot reproduce this with a clean, minimal config, you need to report the issue there.",
            "created_at": "2024-07-29T08:32:03Z",
            "html_url": "https://github.com/neovim/neovim/issues/29900#issuecomment-2255325982",
            "id": 2255325982,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/29900",
            "node_id": "IC_kwDOAPphoM6GbYse",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/2255325982/reactions"
            },
            "updated_at": "2024-07-29T08:32:03Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/2255325982",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/2361214?v=4",
                "events_url": "https://api.github.com/users/clason/events{/privacy}",
                "followers_url": "https://api.github.com/users/clason/followers",
                "following_url": "https://api.github.com/users/clason/following{/other_user}",
                "gists_url": "https://api.github.com/users/clason/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/clason",
                "id": 2361214,
                "login": "clason",
                "node_id": "MDQ6VXNlcjIzNjEyMTQ=",
                "organizations_url": "https://api.github.com/users/clason/orgs",
                "received_events_url": "https://api.github.com/users/clason/received_events",
                "repos_url": "https://api.github.com/users/clason/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/clason/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/clason/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/clason"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "This seems to have nothing to do with core filetype detection. The traceback mentions it because it is when the error happens.\r\n\r\nThe true reason seems to be [this line](https://github.com/LazyVim/LazyVim/blob/12818a6cb499456f4903c5d8e68af43753ebc869/lua/lazyvim/config/autocmds.lua#L130) which indeed compares number (output of `vim.fn.getfsize()`) with something that is possibly `nil`.",
            "created_at": "2024-07-31T15:12:28Z",
            "html_url": "https://github.com/neovim/neovim/issues/29900#issuecomment-2260760705",
            "id": 2260760705,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/29900",
            "node_id": "IC_kwDOAPphoM6GwHiB",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/2260760705/reactions"
            },
            "updated_at": "2024-07-31T15:12:28Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/2260760705",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/24854248?v=4",
                "events_url": "https://api.github.com/users/echasnovski/events{/privacy}",
                "followers_url": "https://api.github.com/users/echasnovski/followers",
                "following_url": "https://api.github.com/users/echasnovski/following{/other_user}",
                "gists_url": "https://api.github.com/users/echasnovski/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/echasnovski",
                "id": 24854248,
                "login": "echasnovski",
                "node_id": "MDQ6VXNlcjI0ODU0MjQ4",
                "organizations_url": "https://api.github.com/users/echasnovski/orgs",
                "received_events_url": "https://api.github.com/users/echasnovski/received_events",
                "repos_url": "https://api.github.com/users/echasnovski/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/echasnovski/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/echasnovski/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/echasnovski"
            }
        },
        {
            "author_association": "NONE",
            "body": "@lukeflo Have you managed to fix it? I have the same issue and this is the only place where I can find someone who has the same error.",
            "created_at": "2024-09-10T11:30:17Z",
            "html_url": "https://github.com/neovim/neovim/issues/29900#issuecomment-2340407301",
            "id": 2340407301,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/29900",
            "node_id": "IC_kwDOAPphoM6Lf8gF",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/2340407301/reactions"
            },
            "updated_at": "2024-09-10T11:30:17Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/2340407301",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/112847866?v=4",
                "events_url": "https://api.github.com/users/Brikkel/events{/privacy}",
                "followers_url": "https://api.github.com/users/Brikkel/followers",
                "following_url": "https://api.github.com/users/Brikkel/following{/other_user}",
                "gists_url": "https://api.github.com/users/Brikkel/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/Brikkel",
                "id": 112847866,
                "login": "Brikkel",
                "node_id": "U_kgDOBrnr-g",
                "organizations_url": "https://api.github.com/users/Brikkel/orgs",
                "received_events_url": "https://api.github.com/users/Brikkel/received_events",
                "repos_url": "https://api.github.com/users/Brikkel/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/Brikkel/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/Brikkel/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/Brikkel"
            }
        },
        {
            "author_association": "NONE",
            "body": "@Brikkel, I had the exact same issue, seems this workaround does the job.\r\nIn one of your nvim config files add\r\n\r\n`vim.g.bigfile_size=1024*1024*1 -- 1M`\r\n\r\nFor context:\r\n- ArchLinux\r\n- nvim v0.10.1\r\n- blank LazyVim configuration in \"Structured setup\" (conf files split in directories), following https://lazy.folke.io/installation\r\n- enabled plugins : catppuccin (theme), LazyVim and Telescope\r\n\r\nI added the above line in the .config/nvim/lua/config/lazy.lua\r\n\r\nHope this helps ! (it doesn't solve the root cause however)\r\n\r\n",
            "created_at": "2024-09-12T10:05:22Z",
            "html_url": "https://github.com/neovim/neovim/issues/29900#issuecomment-2345824245",
            "id": 2345824245,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/29900",
            "node_id": "IC_kwDOAPphoM6L0m_1",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/2345824245/reactions"
            },
            "updated_at": "2024-09-12T10:05:22Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/2345824245",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/4409796?v=4",
                "events_url": "https://api.github.com/users/mysterfr/events{/privacy}",
                "followers_url": "https://api.github.com/users/mysterfr/followers",
                "following_url": "https://api.github.com/users/mysterfr/following{/other_user}",
                "gists_url": "https://api.github.com/users/mysterfr/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/mysterfr",
                "id": 4409796,
                "login": "mysterfr",
                "node_id": "MDQ6VXNlcjQ0MDk3OTY=",
                "organizations_url": "https://api.github.com/users/mysterfr/orgs",
                "received_events_url": "https://api.github.com/users/mysterfr/received_events",
                "repos_url": "https://api.github.com/users/mysterfr/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/mysterfr/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/mysterfr/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/mysterfr"
            }
        }
    ],
    "comments": 5,
    "comments_url": "https://api.github.com/repos/neovim/neovim/issues/29900/comments",
    "created_at": "2024-07-29T08:25:51Z",
    "events_url": "https://api.github.com/repos/neovim/neovim/issues/29900/events",
    "html_url": "https://github.com/neovim/neovim/issues/29900",
    "id": 2434781511,
    "labels": [
        {
            "color": "f9d0c4",
            "default": true,
            "description": "issues reporting wrong behavior",
            "id": 77997474,
            "name": "bug",
            "node_id": "MDU6TGFiZWw3Nzk5NzQ3NA==",
            "url": "https://api.github.com/repos/neovim/neovim/labels/bug"
        },
        {
            "color": "FBCA04",
            "default": false,
            "description": "waiting for reply from the author",
            "id": 248229439,
            "name": "needs:response",
            "node_id": "MDU6TGFiZWwyNDgyMjk0Mzk=",
            "url": "https://api.github.com/repos/neovim/neovim/labels/needs:response"
        },
        {
            "color": "FBCA04",
            "default": false,
            "description": "We need minimal steps to reproduce the issue",
            "id": 298863445,
            "name": "needs:repro",
            "node_id": "MDU6TGFiZWwyOTg4NjM0NDU=",
            "url": "https://api.github.com/repos/neovim/neovim/labels/needs:repro"
        }
    ],
    "labels_url": "https://api.github.com/repos/neovim/neovim/issues/29900/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "I_kwDOAPphoM6RH9FH",
    "number": 29900,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 0,
        "url": "https://api.github.com/repos/neovim/neovim/issues/29900/reactions"
    },
    "repository_url": "https://api.github.com/repos/neovim/neovim",
    "state": "closed",
    "state_reason": "not_planned",
    "timeline_url": "https://api.github.com/repos/neovim/neovim/issues/29900/timeline",
    "title": "After update to 0.10.1 neovim doesn't recognize filetypes anymore",
    "updated_at": "2024-09-12T10:05:23Z",
    "url": "https://api.github.com/repos/neovim/neovim/issues/29900",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/103174551?v=4",
        "events_url": "https://api.github.com/users/lukeflo/events{/privacy}",
        "followers_url": "https://api.github.com/users/lukeflo/followers",
        "following_url": "https://api.github.com/users/lukeflo/following{/other_user}",
        "gists_url": "https://api.github.com/users/lukeflo/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/lukeflo",
        "id": 103174551,
        "login": "lukeflo",
        "node_id": "U_kgDOBiZRlw",
        "organizations_url": "https://api.github.com/users/lukeflo/orgs",
        "received_events_url": "https://api.github.com/users/lukeflo/received_events",
        "repos_url": "https://api.github.com/users/lukeflo/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/lukeflo/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/lukeflo/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/lukeflo"
    }
}