{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "MEMBER",
    "body": "The docs build https://readthedocs.org/projects/pynvim/builds/ is failing since 260a0b922bbd30be4ec32365faf37c2c70a7a4c4 . That commit triggered the build, but its code changes may be unrelated, instead we may need to update some dependencies/configuration: https://github.com/search?q=repo%3Aneovim%2Fpynvim+Sphinx&type=code\r\n\r\nhttps://readthedocs.org/projects/pynvim/builds/22217681/\r\n\r\n```\r\npython -m sphinx -T -E -W --keep-going -b html -d _build/doctrees -D language=en . $READTHEDOCS_OUTPUT/html\r\nRunning Sphinx v7.2.6\r\nmaking output directory... done\r\n\r\nTraceback (most recent call last):\r\n  File \"/home/docs/checkouts/readthedocs.org/user_builds/pynvim/envs/latest/lib/python3.11/site-packages/sphinx/cmd/build.py\", line 293, in build_main\r\n    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,\r\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"/home/docs/checkouts/readthedocs.org/user_builds/pynvim/envs/latest/lib/python3.11/site-packages/sphinx/application.py\", line 272, in __init__\r\n    self._init_builder()\r\n  File \"/home/docs/checkouts/readthedocs.org/user_builds/pynvim/envs/latest/lib/python3.11/site-packages/sphinx/application.py\", line 342, in _init_builder\r\n    self.builder.init()\r\n  File \"/home/docs/checkouts/readthedocs.org/user_builds/pynvim/envs/latest/lib/python3.11/site-packages/sphinx/builders/html/__init__.py\", line 219, in init\r\n    self.init_templates()\r\n  File \"/home/docs/checkouts/readthedocs.org/user_builds/pynvim/envs/latest/lib/python3.11/site-packages/sphinx/builders/html/__init__.py\", line 270, in init_templates\r\n    self.theme = theme_factory.create(themename)\r\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"/home/docs/checkouts/readthedocs.org/user_builds/pynvim/envs/latest/lib/python3.11/site-packages/sphinx/theming.py\", line 230, in create\r\n    raise ThemeError(__('no theme named %r found (missing theme.conf?)') % name)\r\nsphinx.errors.ThemeError: no theme named 'sphinx_rtd_theme' found (missing theme.conf?)\r\n\r\nTheme error:\r\nno theme named 'sphinx_rtd_theme' found (missing theme.conf?)\r\n```\r\n\r\n",
    "closed_at": null,
    "comment_data": [
        {
            "author_association": "CONTRIBUTOR",
            "body": "@justinmk I can't really test because my fork doesn't have the actual action set up that would publis hto readthedocs, but this might fix the issue: https://github.com/wookayin/pynvim/commit/06e9073cad3f721a9984295c7767b7c4739fab45. Not sending a PR because I'm not 100% certain about it.",
            "created_at": "2023-12-10T10:10:52Z",
            "html_url": "https://github.com/neovim/pynvim/issues/552#issuecomment-1848918519",
            "id": 1848918519,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/552",
            "node_id": "IC_kwDOASpKTs5uNEH3",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1848918519/reactions"
            },
            "updated_at": "2023-12-10T10:10:52Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1848918519",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/1009873?v=4",
                "events_url": "https://api.github.com/users/wookayin/events{/privacy}",
                "followers_url": "https://api.github.com/users/wookayin/followers",
                "following_url": "https://api.github.com/users/wookayin/following{/other_user}",
                "gists_url": "https://api.github.com/users/wookayin/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/wookayin",
                "id": 1009873,
                "login": "wookayin",
                "node_id": "MDQ6VXNlcjEwMDk4NzM=",
                "organizations_url": "https://api.github.com/users/wookayin/orgs",
                "received_events_url": "https://api.github.com/users/wookayin/received_events",
                "repos_url": "https://api.github.com/users/wookayin/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/wookayin/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/wookayin/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/wookayin"
            }
        }
    ],
    "comments": 1,
    "comments_url": "https://api.github.com/repos/neovim/pynvim/issues/552/comments",
    "created_at": "2023-12-05T12:34:11Z",
    "events_url": "https://api.github.com/repos/neovim/pynvim/issues/552/events",
    "html_url": "https://github.com/neovim/pynvim/issues/552",
    "id": 2026094554,
    "labels": [
        {
            "color": "C5DEF5",
            "default": false,
            "description": "",
            "id": 6289990498,
            "name": "ci",
            "node_id": "LA_kwDOASpKTs8AAAABdumjYg",
            "url": "https://api.github.com/repos/neovim/pynvim/labels/ci"
        }
    ],
    "labels_url": "https://api.github.com/repos/neovim/pynvim/issues/552/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "I_kwDOASpKTs54w7_a",
    "number": 552,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 1,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 1,
        "url": "https://api.github.com/repos/neovim/pynvim/issues/552/reactions"
    },
    "repository_url": "https://api.github.com/repos/neovim/pynvim",
    "state": "open",
    "state_reason": null,
    "timeline_url": "https://api.github.com/repos/neovim/pynvim/issues/552/timeline",
    "title": "docs (readthedocs) CI is failing",
    "updated_at": "2023-12-10T10:10:53Z",
    "url": "https://api.github.com/repos/neovim/pynvim/issues/552",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/1359421?v=4",
        "events_url": "https://api.github.com/users/justinmk/events{/privacy}",
        "followers_url": "https://api.github.com/users/justinmk/followers",
        "following_url": "https://api.github.com/users/justinmk/following{/other_user}",
        "gists_url": "https://api.github.com/users/justinmk/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/justinmk",
        "id": 1359421,
        "login": "justinmk",
        "node_id": "MDQ6VXNlcjEzNTk0MjE=",
        "organizations_url": "https://api.github.com/users/justinmk/orgs",
        "received_events_url": "https://api.github.com/users/justinmk/received_events",
        "repos_url": "https://api.github.com/users/justinmk/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/justinmk/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/justinmk/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/justinmk"
    }
}