{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "NONE",
    "body": "\r\nCurl is installed in my windows system. I could individually run `curl https://pypi.python.org/pypi/pynvim/json` and no error. However, when i run `neovim :checkhealth`, facing this error in the report. \r\n\r\n\r\n`: checkhealth` output:\r\n\r\n```\r\nPython 3 provider (optional) ~\r\n- pyenv: Path: C:\\Users\\<username>\\.pyenv\\pyenv-win\\bin\\pyenv.BAT\r\n- pyenv: Root: C:\\Users\\<username>\\.pyenv\\pyenv-win\\\r\n- Using: g:python3_host_prog = \"C:/Python312/python.exe\"\r\n- Executable: C:\\Python312\\python.exe\r\n- Python version: 3.12.0\r\n- pynvim version: 0.5.0\r\n- WARNING Could not contact PyPI to get latest version.\r\n- ERROR HTTP request failed: error: curl error with https://pypi.python.org/pypi/pynvim/json: 35\r\n```\r\n",
    "closed_at": null,
    "comment_data": [
        {
            "author_association": "MEMBER",
            "body": "- Does that happen always -- not a temporary problem?\r\n- What is your neovim version?\r\n- Can you try `!curl -sL https://pypi.python.org/pypi/pynvim/json` and does it print JSON data successfully?",
            "created_at": "2023-12-15T05:32:24Z",
            "html_url": "https://github.com/neovim/pynvim/issues/557#issuecomment-1857303724",
            "id": 1857303724,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/557",
            "node_id": "IC_kwDOASpKTs5utDSs",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1857303724/reactions"
            },
            "updated_at": "2023-12-15T05:32:24Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1857303724",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/1009873?v=4",
                "events_url": "https://api.github.com/users/wookayin/events{/privacy}",
                "followers_url": "https://api.github.com/users/wookayin/followers",
                "following_url": "https://api.github.com/users/wookayin/following{/other_user}",
                "gists_url": "https://api.github.com/users/wookayin/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/wookayin",
                "id": 1009873,
                "login": "wookayin",
                "node_id": "MDQ6VXNlcjEwMDk4NzM=",
                "organizations_url": "https://api.github.com/users/wookayin/orgs",
                "received_events_url": "https://api.github.com/users/wookayin/received_events",
                "repos_url": "https://api.github.com/users/wookayin/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/wookayin/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/wookayin/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/wookayin"
            }
        },
        {
            "author_association": "NONE",
            "body": "\r\n1. Yes, the error occurs always\r\n2. NVIM v0.9.4\r\n3. Output of `:!curl =sL https://pypi.python.org/pypi/pynvim/json`\r\n```pwsh\r\ncurl: (3) URL rejected: Bad hostname\r\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\r\n                                 Dload  Upload   Total   Spent    Left  Speed\r\n  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r\ncurl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revoc\r\nation function was unable to check revocation for the certificate.\r\n\r\nshell returned 35\r\n```",
            "created_at": "2023-12-15T17:28:08Z",
            "html_url": "https://github.com/neovim/pynvim/issues/557#issuecomment-1858232801",
            "id": 1858232801,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/557",
            "node_id": "IC_kwDOASpKTs5uwmHh",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1858232801/reactions"
            },
            "updated_at": "2023-12-15T17:28:08Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1858232801",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/3577158?v=4",
                "events_url": "https://api.github.com/users/sudheer82/events{/privacy}",
                "followers_url": "https://api.github.com/users/sudheer82/followers",
                "following_url": "https://api.github.com/users/sudheer82/following{/other_user}",
                "gists_url": "https://api.github.com/users/sudheer82/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/sudheer82",
                "id": 3577158,
                "login": "sudheer82",
                "node_id": "MDQ6VXNlcjM1NzcxNTg=",
                "organizations_url": "https://api.github.com/users/sudheer82/orgs",
                "received_events_url": "https://api.github.com/users/sudheer82/received_events",
                "repos_url": "https://api.github.com/users/sudheer82/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/sudheer82/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/sudheer82/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/sudheer82"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "`-sL`, not `=sL`. Try `:!curl --verbose -fL https://pypi.python.org/pypi/pynvim/json` for debugging.\r\n\r\nFrom the output, there was an issue while validating the certificate. What's the output of `curl --version`?\r\n\r\nAnyway this does not seem relevant to pynvim.",
            "created_at": "2023-12-17T08:46:48Z",
            "html_url": "https://github.com/neovim/pynvim/issues/557#issuecomment-1859075899",
            "id": 1859075899,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/557",
            "node_id": "IC_kwDOASpKTs5uzz87",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1859075899/reactions"
            },
            "updated_at": "2023-12-17T08:47:17Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1859075899",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/1009873?v=4",
                "events_url": "https://api.github.com/users/wookayin/events{/privacy}",
                "followers_url": "https://api.github.com/users/wookayin/followers",
                "following_url": "https://api.github.com/users/wookayin/following{/other_user}",
                "gists_url": "https://api.github.com/users/wookayin/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/wookayin",
                "id": 1009873,
                "login": "wookayin",
                "node_id": "MDQ6VXNlcjEwMDk4NzM=",
                "organizations_url": "https://api.github.com/users/wookayin/orgs",
                "received_events_url": "https://api.github.com/users/wookayin/received_events",
                "repos_url": "https://api.github.com/users/wookayin/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/wookayin/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/wookayin/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/wookayin"
            }
        }
    ],
    "comments": 3,
    "comments_url": "https://api.github.com/repos/neovim/pynvim/issues/557/comments",
    "created_at": "2023-12-15T03:54:34Z",
    "events_url": "https://api.github.com/repos/neovim/pynvim/issues/557/events",
    "html_url": "https://github.com/neovim/pynvim/issues/557",
    "id": 2042848214,
    "labels": [],
    "labels_url": "https://api.github.com/repos/neovim/pynvim/issues/557/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "I_kwDOASpKTs55w2PW",
    "number": 557,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 0,
        "url": "https://api.github.com/repos/neovim/pynvim/issues/557/reactions"
    },
    "repository_url": "https://api.github.com/repos/neovim/pynvim",
    "state": "open",
    "state_reason": null,
    "timeline_url": "https://api.github.com/repos/neovim/pynvim/issues/557/timeline",
    "title": "checkhealth WARNING: Could not contact PyPI to get latest version",
    "updated_at": "2023-12-17T08:47:17Z",
    "url": "https://api.github.com/repos/neovim/pynvim/issues/557",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/3577158?v=4",
        "events_url": "https://api.github.com/users/sudheer82/events{/privacy}",
        "followers_url": "https://api.github.com/users/sudheer82/followers",
        "following_url": "https://api.github.com/users/sudheer82/following{/other_user}",
        "gists_url": "https://api.github.com/users/sudheer82/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/sudheer82",
        "id": 3577158,
        "login": "sudheer82",
        "node_id": "MDQ6VXNlcjM1NzcxNTg=",
        "organizations_url": "https://api.github.com/users/sudheer82/orgs",
        "received_events_url": "https://api.github.com/users/sudheer82/received_events",
        "repos_url": "https://api.github.com/users/sudheer82/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/sudheer82/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/sudheer82/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/sudheer82"
    }
}